# Downloading Gridded Daymet tile NetCDF 's 

## Create interactive map with Daymet using Folium

In [1]:
import folium
import json
m = folium.Map(location=[49, -119], zoom_start=2.2)
style_function = lambda x: {"color":"black"}
with open("Daymet_v4_Tiles.geojson",'r') as f:
    data = json.load(f)
    g_json = folium.GeoJson(data, name="Daymet Tiles",
                            style_function=style_function,
                            popup=folium.GeoJsonPopup(fields=["TileID","Latitude (Max)","Latitude (Min)","Longitude (Max)","Longitude (Min)"])).add_to(m)

folium.TileLayer('Stamen Terrain').add_to(m)
folium.LayerControl().add_to(m)

In [2]:
m #display map

In [3]:
%%sh
bash ../Bash/daymet_tile-nc-retrieval.sh -h

Script to download netCDFs from https://thredds.daac.ornl.gov/thredds/catalog/ornldaac/1840/tiles/catalog.html

Usage: daymet_tile-nc-retrieval.sh [h|s|e|v|t|c] [start_tile] [end_tile]
Options:
h     Print this Help.
s     Specifiy start year. Default is 1980.
e     Specifiy end year. Default is 2021.
v     Specifiy variable list(quoted space delimited list). Default all variables (dayl,prcp,srad,swe,tmax,tmin,vp).
t     Input tiles a list of tiles instead of a range(quoted space delimited list).
c     Set flag to use curl instead of wget.

Examples:
./daymet_tile-nc-retrieval.sh -s 2020 -e 2021 -v "vp" 11207 11209
Download vp netcdfs for tiles 11207, 11208, 11209 between 2020 and 2021.



## Daymet Tile NetCDF Retrieval Script Examples

Download vp nc files for tiles between 11207 and 11209 over years between 2020 and 2021

In [4]:
%%sh
bash ../Bash/daymet_tile-nc-retrieval.sh -s 2020 -e 2021 -v "vp dayl" 11207 11209

--2022-06-10 13:48:16--  https://thredds.daac.ornl.gov/thredds/fileServer/ornldaac/1840/tiles/2020/11207_2020/vp.nc
Resolving thredds.daac.ornl.gov (thredds.daac.ornl.gov)... 160.91.19.90
Connecting to thredds.daac.ornl.gov (thredds.daac.ornl.gov)|160.91.19.90|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72732680 (69M) [application/x-netcdf]
Saving to: ‘11207_2020_vp.nc’

     0K .......... .......... .......... .......... ..........  0%  470K 2m31s
    50K .......... .......... .......... .......... ..........  0%  928K 1m54s
   100K .......... .......... .......... .......... ..........  0% 5.09M 80s
   150K .......... .......... .......... .......... ..........  0% 15.0M 61s
   200K .......... .......... .......... .......... ..........  0% 1.17M 61s
   250K .......... .......... .......... .......... ..........  0% 3.37M 54s
   300K .......... .......... .......... .......... ..........  0% 3.54M 49s
   350K .......... .......... .......... .......... .

  5100K .......... .......... .......... .......... ..........  7% 59.8M 21s
  5150K .......... .......... .......... .......... ..........  7% 44.2M 21s
  5200K .......... .......... .......... .......... ..........  7% 25.2M 21s
  5250K .......... .......... .......... .......... ..........  7% 72.7M 21s
  5300K .......... .......... .......... .......... ..........  7%  248K 23s
  5350K .......... .......... .......... .......... ..........  7% 56.1M 23s
  5400K .......... .......... .......... .......... ..........  7% 42.2M 23s
  5450K .......... .......... .......... .......... ..........  7% 45.0M 22s
  5500K .......... .......... .......... .......... ..........  7% 52.4M 22s
  5550K .......... .......... .......... .......... ..........  7% 34.7M 22s
  5600K .......... .......... .......... .......... ..........  7% 37.9M 22s
  5650K .......... .......... .......... .......... ..........  8% 38.9M 22s
  5700K .......... .......... .......... .......... ..........  8% 38.7M 21s

 10450K .......... .......... .......... .......... .......... 14% 27.4M 20s
 10500K .......... .......... .......... .......... .......... 14% 33.6M 19s
 10550K .......... .......... .......... .......... .......... 14% 51.5M 19s
 10600K .......... .......... .......... .......... .......... 14%  245K 20s
 10650K .......... .......... .......... .......... .......... 15% 34.1M 20s
 10700K .......... .......... .......... .......... .......... 15% 34.8M 20s
 10750K .......... .......... .......... .......... .......... 15% 58.8M 20s
 10800K .......... .......... .......... .......... .......... 15% 52.6M 20s
 10850K .......... .......... .......... .......... .......... 15% 48.9M 20s
 10900K .......... .......... .......... .......... .......... 15% 45.7M 20s
 10950K .......... .......... .......... .......... .......... 15% 35.8M 20s
 11000K .......... .......... .......... .......... .......... 15% 31.0M 20s
 11050K .......... .......... .......... .......... .......... 15% 27.8M 20s

 15800K .......... .......... .......... .......... .......... 22% 66.6M 18s
 15850K .......... .......... .......... .......... .......... 22% 33.0M 18s
 15900K .......... .......... .......... .......... .......... 22% 54.9M 18s
 15950K .......... .......... .......... .......... .......... 22%  245K 18s
 16000K .......... .......... .......... .......... .......... 22% 37.0M 18s
 16050K .......... .......... .......... .......... .......... 22% 50.8M 18s
 16100K .......... .......... .......... .......... .......... 22% 44.2M 18s
 16150K .......... .......... .......... .......... .......... 22% 45.1M 18s
 16200K .......... .......... .......... .......... .......... 22% 47.5M 18s
 16250K .......... .......... .......... .......... .......... 22% 39.2M 18s
 16300K .......... .......... .......... .......... .......... 23% 25.8M 18s
 16350K .......... .......... .......... .......... .......... 23% 22.7M 18s
 16400K .......... .......... .......... .......... .......... 23% 24.4M 18s

 21150K .......... .......... .......... .......... .......... 29% 66.6M 16s
 21200K .......... .......... .......... .......... .......... 29% 60.1M 16s
 21250K .......... .......... .......... .......... .......... 29% 67.6M 16s
 21300K .......... .......... .......... .......... .......... 30%  246K 16s
 21350K .......... .......... .......... .......... .......... 30% 42.7M 16s
 21400K .......... .......... .......... .......... .......... 30% 30.4M 16s
 21450K .......... .......... .......... .......... .......... 30% 39.3M 16s
 21500K .......... .......... .......... .......... .......... 30% 35.4M 16s
 21550K .......... .......... .......... .......... .......... 30% 60.1M 16s
 21600K .......... .......... .......... .......... .......... 30% 51.8M 16s
 21650K .......... .......... .......... .......... .......... 30% 48.0M 16s
 21700K .......... .......... .......... .......... .......... 30% 61.2M 16s
 21750K .......... .......... .......... .......... .......... 30% 34.5M 16s

 26500K .......... .......... .......... .......... .......... 37% 73.4M 14s
 26550K .......... .......... .......... .......... .......... 37%  246K 15s
 26600K .......... .......... .......... .......... .......... 37% 31.6M 15s
 26650K .......... .......... .......... .......... .......... 37% 33.2M 15s
 26700K .......... .......... .......... .......... .......... 37% 26.4M 15s
 26750K .......... .......... .......... .......... .......... 37% 52.5M 15s
 26800K .......... .......... .......... .......... .......... 37% 41.5M 14s
 26850K .......... .......... .......... .......... .......... 37% 44.1M 14s
 26900K .......... .......... .......... .......... .......... 37% 58.5M 14s
 26950K .......... .......... .......... .......... .......... 38% 35.3M 14s
 27000K .......... .......... .......... .......... .......... 38% 51.7M 14s
 27050K .......... .......... .......... .......... .......... 38% 36.5M 14s
 27100K .......... .......... .......... .......... .......... 38% 20.7M 14s

 31850K .......... .......... .......... .......... .......... 44%  249K 13s
 31900K .......... .......... .......... .......... .......... 44%  130M 13s
 31950K .......... .......... .......... .......... .......... 45%  211M 13s
 32000K .......... .......... .......... .......... .......... 45%  151M 13s
 32050K .......... .......... .......... .......... .......... 45%  172M 13s
 32100K .......... .......... .......... .......... .......... 45%  198M 13s
 32150K .......... .......... .......... .......... .......... 45%  238M 13s
 32200K .......... .......... .......... .......... .......... 45%  212M 13s
 32250K .......... .......... .......... .......... .......... 45%  187M 13s
 32300K .......... .......... .......... .......... .......... 45%  223M 13s
 32350K .......... .......... .......... .......... .......... 45%  141M 13s
 32400K .......... .......... .......... .......... .......... 45%  143M 13s
 32450K .......... .......... .......... .......... .......... 45%  247K 13s

 37200K .......... .......... .......... .......... .......... 52% 56.1M 11s
 37250K .......... .......... .......... .......... .......... 52% 50.0M 11s
 37300K .......... .......... .......... .......... .......... 52% 62.7M 11s
 37350K .......... .......... .......... .......... .......... 52% 44.4M 11s
 37400K .......... .......... .......... .......... .......... 52% 34.8M 11s
 37450K .......... .......... .......... .......... .......... 52% 37.6M 11s
 37500K .......... .......... .......... .......... .......... 52% 32.5M 11s
 37550K .......... .......... .......... .......... .......... 52% 41.4M 11s
 37600K .......... .......... .......... .......... .......... 53% 81.3M 11s
 37650K .......... .......... .......... .......... .......... 53% 57.6M 11s
 37700K .......... .......... .......... .......... .......... 53%  101M 11s
 37750K .......... .......... .......... .......... .......... 53%  247K 11s
 37800K .......... .......... .......... .......... .......... 53% 84.1M 11s

 42550K .......... .......... .......... .......... .......... 59%  116M 9s
 42600K .......... .......... .......... .......... .......... 60%  155M 9s
 42650K .......... .......... .......... .......... .......... 60% 90.8M 9s
 42700K .......... .......... .......... .......... .......... 60%  105M 9s
 42750K .......... .......... .......... .......... .......... 60%  119M 9s
 42800K .......... .......... .......... .......... .......... 60% 75.1M 9s
 42850K .......... .......... .......... .......... .......... 60%  134M 9s
 42900K .......... .......... .......... .......... .......... 60%  119M 9s
 42950K .......... .......... .......... .......... .......... 60%  249K 9s
 43000K .......... .......... .......... .......... .......... 60% 56.2M 9s
 43050K .......... .......... .......... .......... .......... 60% 65.1M 9s
 43100K .......... .......... .......... .......... .......... 60% 42.6M 9s
 43150K .......... .......... .......... .......... .......... 60% 27.8M 9s
 43200K ....

 47950K .......... .......... .......... .......... .......... 67% 48.1M 8s
 48000K .......... .......... .......... .......... .......... 67% 64.5M 7s
 48050K .......... .......... .......... .......... .......... 67% 63.3M 7s
 48100K .......... .......... .......... .......... .......... 67% 44.9M 7s
 48150K .......... .......... .......... .......... .......... 67% 41.6M 7s
 48200K .......... .......... .......... .......... .......... 67% 63.0M 7s
 48250K .......... .......... .......... .......... .......... 68% 44.7M 7s
 48300K .......... .......... .......... .......... .......... 68%  244K 7s
 48350K .......... .......... .......... .......... .......... 68% 43.4M 7s
 48400K .......... .......... .......... .......... .......... 68% 53.9M 7s
 48450K .......... .......... .......... .......... .......... 68% 47.6M 7s
 48500K .......... .......... .......... .......... .......... 68% 63.6M 7s
 48550K .......... .......... .......... .......... .......... 68% 69.6M 7s
 48600K ....

 53350K .......... .......... .......... .......... .......... 75% 32.5M 6s
 53400K .......... .......... .......... .......... .......... 75% 33.1M 6s
 53450K .......... .......... .......... .......... .......... 75% 32.7M 6s
 53500K .......... .......... .......... .......... .......... 75% 41.5M 6s
 53550K .......... .......... .......... .......... .......... 75% 31.8M 6s
 53600K .......... .......... .......... .......... .......... 75%  245K 6s
 53650K .......... .......... .......... .......... .......... 75% 27.3M 6s
 53700K .......... .......... .......... .......... .......... 75% 39.0M 6s
 53750K .......... .......... .......... .......... .......... 75% 30.2M 6s
 53800K .......... .......... .......... .......... .......... 75% 43.7M 6s
 53850K .......... .......... .......... .......... .......... 75% 45.0M 6s
 53900K .......... .......... .......... .......... .......... 75% 50.4M 6s
 53950K .......... .......... .......... .......... .......... 76% 51.0M 6s
 54000K ....

 58750K .......... .......... .......... .......... .......... 82% 18.2M 4s
 58800K .......... .......... .......... .......... .......... 82% 28.2M 4s
 58850K .......... .......... .......... .......... .......... 82%  247K 4s
 58900K .......... .......... .......... .......... .......... 82% 45.6M 4s
 58950K .......... .......... .......... .......... .......... 83% 67.8M 4s
 59000K .......... .......... .......... .......... .......... 83% 64.2M 4s
 59050K .......... .......... .......... .......... .......... 83% 42.9M 4s
 59100K .......... .......... .......... .......... .......... 83% 61.1M 4s
 59150K .......... .......... .......... .......... .......... 83% 81.7M 4s
 59200K .......... .......... .......... .......... .......... 83% 75.9M 4s
 59250K .......... .......... .......... .......... .......... 83% 90.7M 4s
 59300K .......... .......... .......... .......... .......... 83% 77.8M 4s
 59350K .......... .......... .......... .......... .......... 83% 65.2M 4s
 59400K ....

 64150K .......... .......... .......... .......... .......... 90%  141M 2s
 64200K .......... .......... .......... .......... .......... 90%  155M 2s
 64250K .......... .......... .......... .......... .......... 90%  133M 2s
 64300K .......... .......... .......... .......... .......... 90%  179M 2s
 64350K .......... .......... .......... .......... .......... 90%  150M 2s
 64400K .......... .......... .......... .......... .......... 90%  175M 2s
 64450K .......... .......... .......... .......... .......... 90%  218M 2s
 64500K .......... .......... .......... .......... .......... 90%  216M 2s
 64550K .......... .......... .......... .......... .......... 90%  185M 2s
 64600K .......... .......... .......... .......... .......... 91%  200M 2s
 64650K .......... .......... .......... .......... .......... 91%  222M 2s
 64700K .......... .......... .......... .......... .......... 91%  246K 2s
 64750K .......... .......... .......... .......... .......... 91% 66.4M 2s
 64800K ....

 69550K .......... .......... .......... .......... .......... 97% 25.2M 0s
 69600K .......... .......... .......... .......... .......... 98% 35.2M 0s
 69650K .......... .......... .......... .......... .......... 98% 27.8M 0s
 69700K .......... .......... .......... .......... .......... 98% 42.5M 0s
 69750K .......... .......... .......... .......... .......... 98% 46.5M 0s
 69800K .......... .......... .......... .......... .......... 98% 23.8M 0s
 69850K .......... .......... .......... .......... .......... 98% 66.7M 0s
 69900K .......... .......... .......... .......... .......... 98% 88.1M 0s
 69950K .......... .......... .......... .......... .......... 98% 55.5M 0s
 70000K .......... .......... .......... .......... .......... 98%  247K 0s
 70050K .......... .......... .......... .......... .......... 98%  146M 0s
 70100K .......... .......... .......... .......... .......... 98% 70.5M 0s
 70150K .......... .......... .......... .......... .......... 98%  175M 0s
 70200K ....

  3550K .......... .......... .......... .......... ..........  5% 52.8M 25s
  3600K .......... .......... .......... .......... ..........  5% 57.0M 24s
  3650K .......... .......... .......... .......... ..........  5% 62.2M 24s
  3700K .......... .......... .......... .......... ..........  5% 59.5M 24s
  3750K .......... .......... .......... .......... ..........  5% 35.0M 23s
  3800K .......... .......... .......... .......... ..........  5% 61.8M 23s
  3850K .......... .......... .......... .......... ..........  5% 75.0M 23s
  3900K .......... .......... .......... .......... ..........  5% 58.6M 22s
  3950K .......... .......... .......... .......... ..........  5% 50.3M 22s
  4000K .......... .......... .......... .......... ..........  5% 43.1M 22s
  4050K .......... .......... .......... .......... ..........  5% 44.1M 22s
  4100K .......... .......... .......... .......... ..........  5% 53.3M 21s
  4150K .......... .......... .......... .......... ..........  5%  247K 24s

  8900K .......... .......... .......... .......... .......... 12% 53.7M 21s
  8950K .......... .......... .......... .......... .......... 12% 65.7M 21s
  9000K .......... .......... .......... .......... .......... 12% 70.8M 21s
  9050K .......... .......... .......... .......... .......... 12% 45.7M 21s
  9100K .......... .......... .......... .......... .......... 12% 60.9M 20s
  9150K .......... .......... .......... .......... .......... 12% 57.4M 20s
  9200K .......... .......... .......... .......... .......... 13% 55.0M 20s
  9250K .......... .......... .......... .......... .......... 13% 63.4M 20s
  9300K .......... .......... .......... .......... .......... 13% 67.5M 20s
  9350K .......... .......... .......... .......... .......... 13% 56.5M 20s
  9400K .......... .......... .......... .......... .......... 13%  247K 21s
  9450K .......... .......... .......... .......... .......... 13% 50.4M 21s
  9500K .......... .......... .......... .......... .......... 13% 65.3M 21s

 14250K .......... .......... .......... .......... .......... 20% 51.8M 19s
 14300K .......... .......... .......... .......... .......... 20% 42.9M 19s
 14350K .......... .......... .......... .......... .......... 20% 41.4M 19s
 14400K .......... .......... .......... .......... .......... 20% 45.3M 19s
 14450K .......... .......... .......... .......... .......... 20% 87.4M 19s
 14500K .......... .......... .......... .......... .......... 20% 67.4M 18s
 14550K .......... .......... .......... .......... .......... 20% 73.7M 18s
 14600K .......... .......... .......... .......... .......... 20% 58.6M 18s
 14650K .......... .......... .......... .......... .......... 20% 73.8M 18s
 14700K .......... .......... .......... .......... .......... 20%  247K 19s
 14750K .......... .......... .......... .......... .......... 20% 68.5M 19s
 14800K .......... .......... .......... .......... .......... 20%  116M 19s
 14850K .......... .......... .......... .......... .......... 20% 98.2M 19s

 19600K .......... .......... .......... .......... .......... 27% 46.1M 17s
 19650K .......... .......... .......... .......... .......... 27% 29.1M 17s
 19700K .......... .......... .......... .......... .......... 27% 27.2M 17s
 19750K .......... .......... .......... .......... .......... 27% 32.6M 17s
 19800K .......... .......... .......... .......... .......... 27% 32.9M 17s
 19850K .......... .......... .......... .......... .......... 28% 19.5M 17s
 19900K .......... .......... .......... .......... .......... 28% 34.0M 17s
 19950K .......... .......... .......... .......... .......... 28% 44.6M 17s
 20000K .......... .......... .......... .......... .......... 28%  247K 17s
 20050K .......... .......... .......... .......... .......... 28% 42.8M 17s
 20100K .......... .......... .......... .......... .......... 28% 45.9M 17s
 20150K .......... .......... .......... .......... .......... 28% 46.2M 17s
 20200K .......... .......... .......... .......... .......... 28% 51.2M 17s

 24950K .......... .......... .......... .......... .......... 35%  112M 15s
 25000K .......... .......... .......... .......... .......... 35% 92.2M 15s
 25050K .......... .......... .......... .......... .......... 35% 75.9M 15s
 25100K .......... .......... .......... .......... .......... 35%  101M 15s
 25150K .......... .......... .......... .......... .......... 35% 82.1M 15s
 25200K .......... .......... .......... .......... .......... 35% 93.0M 15s
 25250K .......... .......... .......... .......... .......... 35% 69.6M 15s
 25300K .......... .......... .......... .......... .......... 35%  249K 15s
 25350K .......... .......... .......... .......... .......... 35%  117M 15s
 25400K .......... .......... .......... .......... .......... 35%  169M 15s
 25450K .......... .......... .......... .......... .......... 35%  196M 15s
 25500K .......... .......... .......... .......... .......... 35%  231M 15s
 25550K .......... .......... .......... .......... .......... 36%  208M 15s

 30300K .......... .......... .......... .......... .......... 42% 44.9M 13s
 30350K .......... .......... .......... .......... .......... 42% 47.0M 13s
 30400K .......... .......... .......... .......... .......... 42% 35.9M 13s
 30450K .......... .......... .......... .......... .......... 42% 37.8M 13s
 30500K .......... .......... .......... .......... .......... 43%  246K 13s
 30550K .......... .......... .......... .......... .......... 43% 50.5M 13s
 30600K .......... .......... .......... .......... .......... 43% 45.0M 13s
 30650K .......... .......... .......... .......... .......... 43% 57.0M 13s
 30700K .......... .......... .......... .......... .......... 43% 52.0M 13s
 30750K .......... .......... .......... .......... .......... 43% 56.1M 13s
 30800K .......... .......... .......... .......... .......... 43% 64.0M 13s
 30850K .......... .......... .......... .......... .......... 43% 76.9M 13s
 30900K .......... .......... .......... .......... .......... 43% 47.9M 13s

 35650K .......... .......... .......... .......... .......... 50%  145M 11s
 35700K .......... .......... .......... .......... .......... 50%  124M 11s
 35750K .......... .......... .......... .......... .......... 50%  248K 12s
 35800K .......... .......... .......... .......... .......... 50% 43.8M 12s
 35850K .......... .......... .......... .......... .......... 50% 52.1M 12s
 35900K .......... .......... .......... .......... .......... 50% 26.4M 12s
 35950K .......... .......... .......... .......... .......... 50% 33.4M 11s
 36000K .......... .......... .......... .......... .......... 50% 52.4M 11s
 36050K .......... .......... .......... .......... .......... 50% 28.3M 11s
 36100K .......... .......... .......... .......... .......... 50% 29.2M 11s
 36150K .......... .......... .......... .......... .......... 50% 14.6M 11s
 36200K .......... .......... .......... .......... .......... 51% 22.5M 11s
 36250K .......... .......... .......... .......... .......... 51% 13.1M 11s

 41000K .......... .......... .......... .......... .......... 57% 52.3M 10s
 41050K .......... .......... .......... .......... .......... 57% 55.1M 10s
 41100K .......... .......... .......... .......... .......... 57% 51.9M 10s
 41150K .......... .......... .......... .......... .......... 58%  246K 10s
 41200K .......... .......... .......... .......... .......... 58% 61.0M 10s
 41250K .......... .......... .......... .......... .......... 58% 44.4M 10s
 41300K .......... .......... .......... .......... .......... 58% 39.7M 10s
 41350K .......... .......... .......... .......... .......... 58% 25.4M 10s
 41400K .......... .......... .......... .......... .......... 58% 63.9M 10s
 41450K .......... .......... .......... .......... .......... 58% 48.9M 10s
 41500K .......... .......... .......... .......... .......... 58% 58.0M 10s
 41550K .......... .......... .......... .......... .......... 58% 46.7M 10s
 41600K .......... .......... .......... .......... .......... 58% 49.2M 10s

 46400K .......... .......... .......... .......... .......... 65% 30.5M 8s
 46450K .......... .......... .......... .......... .......... 65% 52.1M 8s
 46500K .......... .......... .......... .......... .......... 65%  246K 8s
 46550K .......... .......... .......... .......... .......... 65% 60.4M 8s
 46600K .......... .......... .......... .......... .......... 65% 50.7M 8s
 46650K .......... .......... .......... .......... .......... 65% 51.6M 8s
 46700K .......... .......... .......... .......... .......... 65% 48.4M 8s
 46750K .......... .......... .......... .......... .......... 65% 43.1M 8s
 46800K .......... .......... .......... .......... .......... 65% 43.1M 8s
 46850K .......... .......... .......... .......... .......... 66% 39.7M 8s
 46900K .......... .......... .......... .......... .......... 66% 48.4M 8s
 46950K .......... .......... .......... .......... .......... 66% 30.3M 8s
 47000K .......... .......... .......... .......... .......... 66% 37.5M 8s
 47050K ....

 51800K .......... .......... .......... .......... .......... 72% 29.7M 6s
 51850K .......... .......... .......... .......... .......... 73%  245K 6s
 51900K .......... .......... .......... .......... .......... 73% 45.7M 6s
 51950K .......... .......... .......... .......... .......... 73% 45.3M 6s
 52000K .......... .......... .......... .......... .......... 73% 47.6M 6s
 52050K .......... .......... .......... .......... .......... 73% 58.4M 6s
 52100K .......... .......... .......... .......... .......... 73% 32.6M 6s
 52150K .......... .......... .......... .......... .......... 73% 55.9M 6s
 52200K .......... .......... .......... .......... .......... 73% 35.8M 6s
 52250K .......... .......... .......... .......... .......... 73% 33.7M 6s
 52300K .......... .......... .......... .......... .......... 73% 51.9M 6s
 52350K .......... .......... .......... .......... .......... 73% 29.3M 6s
 52400K .......... .......... .......... .......... .......... 73% 57.2M 6s
 52450K ....

 57200K .......... .......... .......... .......... .......... 80% 78.6M 5s
 57250K .......... .......... .......... .......... .......... 80% 80.8M 4s
 57300K .......... .......... .......... .......... .......... 80% 80.3M 4s
 57350K .......... .......... .......... .......... .......... 80%  121M 4s
 57400K .......... .......... .......... .......... .......... 80% 71.1M 4s
 57450K .......... .......... .......... .......... .......... 80% 52.2M 4s
 57500K .......... .......... .......... .......... .......... 81% 65.1M 4s
 57550K .......... .......... .......... .......... .......... 81% 95.8M 4s
 57600K .......... .......... .......... .......... .......... 81% 90.5M 4s
 57650K .......... .......... .......... .......... .......... 81% 98.2M 4s
 57700K .......... .......... .......... .......... .......... 81%  144M 4s
 57750K .......... .......... .......... .......... .......... 81% 76.2M 4s
 57800K .......... .......... .......... .......... .......... 81%  248K 4s
 57850K ....

 62600K .......... .......... .......... .......... .......... 88% 39.5M 3s
 62650K .......... .......... .......... .......... .......... 88% 54.1M 3s
 62700K .......... .......... .......... .......... .......... 88% 41.1M 3s
 62750K .......... .......... .......... .......... .......... 88% 44.8M 3s
 62800K .......... .......... .......... .......... .......... 88% 49.5M 3s
 62850K .......... .......... .......... .......... .......... 88% 55.1M 3s
 62900K .......... .......... .......... .......... .......... 88% 53.1M 3s
 62950K .......... .......... .......... .......... .......... 88% 27.2M 3s
 63000K .......... .......... .......... .......... .......... 88% 46.9M 3s
 63050K .......... .......... .......... .......... .......... 88%  247K 3s
 63100K .......... .......... .......... .......... .......... 88%  119M 3s
 63150K .......... .......... .......... .......... .......... 88%  189M 3s
 63200K .......... .......... .......... .......... .......... 89%  119M 3s
 63250K ....

 68000K .......... .......... .......... .......... .......... 95% 44.8M 1s
 68050K .......... .......... .......... .......... .......... 95% 43.2M 1s
 68100K .......... .......... .......... .......... .......... 95% 41.2M 1s
 68150K .......... .......... .......... .......... .......... 96% 88.1M 1s
 68200K .......... .......... .......... .......... .......... 96% 28.1M 1s
 68250K .......... .......... .......... .......... .......... 96% 25.3M 1s
 68300K .......... .......... .......... .......... .......... 96%  247K 1s
 68350K .......... .......... .......... .......... .......... 96% 39.5M 1s
 68400K .......... .......... .......... .......... .......... 96% 43.6M 1s
 68450K .......... .......... .......... .......... .......... 96% 46.2M 1s
 68500K .......... .......... .......... .......... .......... 96% 51.7M 1s
 68550K .......... .......... .......... .......... .......... 96% 46.0M 1s
 68600K .......... .......... .......... .......... .......... 96% 45.9M 1s
 68650K ....

  2000K .......... .......... .......... .......... ..........  2% 3.41M 26s
  2050K .......... .......... .......... .......... ..........  2% 98.9M 25s
  2100K .......... .......... .......... .......... ..........  2% 10.5M 25s
  2150K .......... .......... .......... .......... ..........  2% 3.79M 24s
  2200K .......... .......... .......... .......... ..........  3% 2.42M 24s
  2250K .......... .......... .......... .......... ..........  3% 1.65M 25s
  2300K .......... .......... .......... .......... ..........  3% 4.42M 25s
  2350K .......... .......... .......... .......... ..........  3%  920K 26s
  2400K .......... .......... .......... .......... ..........  3% 63.7M 25s
  2450K .......... .......... .......... .......... ..........  3% 5.50M 25s
  2500K .......... .......... .......... .......... ..........  3% 9.66M 25s
  2550K .......... .......... .......... .......... ..........  3% 5.99M 24s
  2600K .......... .......... .......... .......... ..........  3% 8.57M 24s

  7350K .......... .......... .......... .......... .......... 10% 35.4M 23s
  7400K .......... .......... .......... .......... .......... 10% 45.9M 22s
  7450K .......... .......... .......... .......... .......... 10% 50.0M 22s
  7500K .......... .......... .......... .......... .......... 10% 57.3M 22s
  7550K .......... .......... .......... .......... .......... 10% 50.2M 22s
  7600K .......... .......... .......... .......... .......... 10% 32.0M 22s
  7650K .......... .......... .......... .......... .......... 10% 30.4M 22s
  7700K .......... .......... .......... .......... .......... 10% 62.8M 22s
  7750K .......... .......... .......... .......... .......... 10% 50.4M 21s
  7800K .......... .......... .......... .......... .......... 10% 55.9M 21s
  7850K .......... .......... .......... .......... .......... 10%  245K 23s
  7900K .......... .......... .......... .......... .......... 10% 47.5M 23s
  7950K .......... .......... .......... .......... .......... 10% 39.3M 23s

 12700K .......... .......... .......... .......... .......... 17% 85.4M 20s
 12750K .......... .......... .......... .......... .......... 17% 56.7M 20s
 12800K .......... .......... .......... .......... .......... 17% 56.3M 20s
 12850K .......... .......... .......... .......... .......... 17% 88.2M 20s
 12900K .......... .......... .......... .......... .......... 17% 44.2M 20s
 12950K .......... .......... .......... .......... .......... 17% 44.2M 20s
 13000K .......... .......... .......... .......... .......... 17%  125M 20s
 13050K .......... .......... .......... .......... .......... 17%  248K 21s
 13100K .......... .......... .......... .......... .......... 17% 33.8M 20s
 13150K .......... .......... .......... .......... .......... 17% 52.0M 20s
 13200K .......... .......... .......... .......... .......... 17% 36.2M 20s
 13250K .......... .......... .......... .......... .......... 18% 35.4M 20s
 13300K .......... .......... .......... .......... .......... 18% 51.7M 20s

 18050K .......... .......... .......... .......... .......... 24% 51.4M 18s
 18100K .......... .......... .......... .......... .......... 24% 24.1M 18s
 18150K .......... .......... .......... .......... .......... 24% 37.2M 18s
 18200K .......... .......... .......... .......... .......... 24% 63.4M 18s
 18250K .......... .......... .......... .......... .......... 24% 83.2M 18s
 18300K .......... .......... .......... .......... .......... 24% 88.2M 18s
 18350K .......... .......... .......... .......... .......... 24% 70.4M 18s
 18400K .......... .......... .......... .......... .......... 25%  245K 18s
 18450K .......... .......... .......... .......... .......... 25% 43.2M 18s
 18500K .......... .......... .......... .......... .......... 25% 34.2M 18s
 18550K .......... .......... .......... .......... .......... 25% 43.5M 18s
 18600K .......... .......... .......... .......... .......... 25% 37.4M 18s
 18650K .......... .......... .......... .......... .......... 25% 29.6M 18s

 23400K .......... .......... .......... .......... .......... 31% 21.2M 16s
 23450K .......... .......... .......... .......... .......... 31%  108M 16s
 23500K .......... .......... .......... .......... .......... 31% 54.0M 16s
 23550K .......... .......... .......... .......... .......... 32% 56.8M 16s
 23600K .......... .......... .......... .......... .......... 32% 82.0M 16s
 23650K .......... .......... .......... .......... .......... 32% 69.8M 16s
 23700K .......... .......... .......... .......... .......... 32%  248K 17s
 23750K .......... .......... .......... .......... .......... 32% 52.6M 17s
 23800K .......... .......... .......... .......... .......... 32% 51.9M 16s
 23850K .......... .......... .......... .......... .......... 32% 48.2M 16s
 23900K .......... .......... .......... .......... .......... 32% 36.9M 16s
 23950K .......... .......... .......... .......... .......... 32% 30.2M 16s
 24000K .......... .......... .......... .......... .......... 32% 29.8M 16s

 28750K .......... .......... .......... .......... .......... 39% 35.6M 15s
 28800K .......... .......... .......... .......... .......... 39% 25.7M 15s
 28850K .......... .......... .......... .......... .......... 39% 37.4M 15s
 28900K .......... .......... .......... .......... .......... 39% 58.0M 15s
 28950K .......... .......... .......... .......... .......... 39% 40.9M 14s
 29000K .......... .......... .......... .......... .......... 39%  245K 15s
 29050K .......... .......... .......... .......... .......... 39%  128M 15s
 29100K .......... .......... .......... .......... .......... 39% 75.7M 15s
 29150K .......... .......... .......... .......... .......... 39%  119M 15s
 29200K .......... .......... .......... .......... .......... 39%  142M 15s
 29250K .......... .......... .......... .......... .......... 39%  100M 15s
 29300K .......... .......... .......... .......... .......... 39% 84.3M 15s
 29350K .......... .......... .......... .......... .......... 39%  121M 14s

 34100K .......... .......... .......... .......... .......... 46% 36.6M 13s
 34150K .......... .......... .......... .......... .......... 46% 39.2M 13s
 34200K .......... .......... .......... .......... .......... 46%  246K 13s
 34250K .......... .......... .......... .......... .......... 46% 23.3M 13s
 34300K .......... .......... .......... .......... .......... 46% 43.9M 13s
 34350K .......... .......... .......... .......... .......... 46% 36.5M 13s
 34400K .......... .......... .......... .......... .......... 46% 36.7M 13s
 34450K .......... .......... .......... .......... .......... 46% 35.7M 13s
 34500K .......... .......... .......... .......... .......... 46% 62.2M 13s
 34550K .......... .......... .......... .......... .......... 47% 57.0M 13s
 34600K .......... .......... .......... .......... .......... 47% 14.9M 13s
 34650K .......... .......... .......... .......... .......... 47% 30.5M 13s
 34700K .......... .......... .......... .......... .......... 47% 70.2M 13s

 39450K .......... .......... .......... .......... .......... 53% 24.5M 11s
 39500K .......... .......... .......... .......... .......... 53% 23.3M 11s
 39550K .......... .......... .......... .......... .......... 53% 29.7M 11s
 39600K .......... .......... .......... .......... .......... 53%  245K 11s
 39650K .......... .......... .......... .......... .......... 53% 64.5M 11s
 39700K .......... .......... .......... .......... .......... 53%  114M 11s
 39750K .......... .......... .......... .......... .......... 54%  108M 11s
 39800K .......... .......... .......... .......... .......... 54% 37.4M 11s
 39850K .......... .......... .......... .......... .......... 54%  113M 11s
 39900K .......... .......... .......... .......... .......... 54%  109M 11s
 39950K .......... .......... .......... .......... .......... 54%  101M 11s
 40000K .......... .......... .......... .......... .......... 54%  114M 11s
 40050K .......... .......... .......... .......... .......... 54% 83.5M 11s

 44800K .......... .......... .......... .......... .......... 60% 21.5M 9s
 44850K .......... .......... .......... .......... .......... 60% 30.0M 9s
 44900K .......... .......... .......... .......... .......... 61%  245K 9s
 44950K .......... .......... .......... .......... .......... 61% 51.8M 9s
 45000K .......... .......... .......... .......... .......... 61% 45.0M 9s
 45050K .......... .......... .......... .......... .......... 61% 41.9M 9s
 45100K .......... .......... .......... .......... .......... 61% 48.5M 9s
 45150K .......... .......... .......... .......... .......... 61% 48.3M 9s
 45200K .......... .......... .......... .......... .......... 61% 48.1M 9s
 45250K .......... .......... .......... .......... .......... 61% 50.7M 9s
 45300K .......... .......... .......... .......... .......... 61% 45.4M 9s
 45350K .......... .......... .......... .......... .......... 61% 49.5M 9s
 45400K .......... .......... .......... .......... .......... 61% 28.4M 9s
 45450K ....

 50200K .......... .......... .......... .......... .......... 68%  247K 8s
 50250K .......... .......... .......... .......... .......... 68% 34.1M 8s
 50300K .......... .......... .......... .......... .......... 68% 42.6M 8s
 50350K .......... .......... .......... .......... .......... 68% 48.2M 8s
 50400K .......... .......... .......... .......... .......... 68% 48.6M 8s
 50450K .......... .......... .......... .......... .......... 68% 57.6M 8s
 50500K .......... .......... .......... .......... .......... 68% 51.2M 8s
 50550K .......... .......... .......... .......... .......... 68% 49.5M 8s
 50600K .......... .......... .......... .......... .......... 68% 54.9M 8s
 50650K .......... .......... .......... .......... .......... 68% 44.1M 7s
 50700K .......... .......... .......... .......... .......... 68% 37.3M 7s
 50750K .......... .......... .......... .......... .......... 69% 42.5M 7s
 50800K .......... .......... .......... .......... .......... 69% 35.3M 7s
 50850K ....

 55600K .......... .......... .......... .......... .......... 75% 54.0M 6s
 55650K .......... .......... .......... .......... .......... 75% 51.5M 6s
 55700K .......... .......... .......... .......... .......... 75% 47.1M 6s
 55750K .......... .......... .......... .......... .......... 75% 65.8M 6s
 55800K .......... .......... .......... .......... .......... 75% 32.6M 6s
 55850K .......... .......... .......... .......... .......... 75% 46.9M 6s
 55900K .......... .......... .......... .......... .......... 76% 34.5M 6s
 55950K .......... .......... .......... .......... .......... 76% 44.4M 6s
 56000K .......... .......... .......... .......... .......... 76% 55.9M 6s
 56050K .......... .......... .......... .......... .......... 76% 42.7M 6s
 56100K .......... .......... .......... .......... .......... 76% 32.7M 6s
 56150K .......... .......... .......... .......... .......... 76% 25.0M 6s
 56200K .......... .......... .......... .......... .......... 76%  246K 6s
 56250K ....

 61000K .......... .......... .......... .......... .......... 82% 28.9M 4s
 61050K .......... .......... .......... .......... .......... 82% 55.5M 4s
 61100K .......... .......... .......... .......... .......... 83% 44.8M 4s
 61150K .......... .......... .......... .......... .......... 83% 24.4M 4s
 61200K .......... .......... .......... .......... .......... 83% 29.3M 4s
 61250K .......... .......... .......... .......... .......... 83% 29.2M 4s
 61300K .......... .......... .......... .......... .......... 83% 33.6M 4s
 61350K .......... .......... .......... .......... .......... 83% 36.0M 4s
 61400K .......... .......... .......... .......... .......... 83% 58.1M 4s
 61450K .......... .......... .......... .......... .......... 83% 58.4M 4s
 61500K .......... .......... .......... .......... .......... 83% 51.2M 4s
 61550K .......... .......... .......... .......... .......... 83%  245K 4s
 61600K .......... .......... .......... .......... .......... 83% 33.2M 4s
 61650K ....

 66400K .......... .......... .......... .......... .......... 90% 33.2M 2s
 66450K .......... .......... .......... .......... .......... 90% 64.2M 2s
 66500K .......... .......... .......... .......... .......... 90% 70.4M 2s
 66550K .......... .......... .......... .......... .......... 90% 82.6M 2s
 66600K .......... .......... .......... .......... .......... 90%  100M 2s
 66650K .......... .......... .......... .......... .......... 90%  113M 2s
 66700K .......... .......... .......... .......... .......... 90% 65.6M 2s
 66750K .......... .......... .......... .......... .......... 90% 84.6M 2s
 66800K .......... .......... .......... .......... .......... 90%  248K 2s
 66850K .......... .......... .......... .......... .......... 90% 84.8M 2s
 66900K .......... .......... .......... .......... .......... 90%  106M 2s
 66950K .......... .......... .......... .......... .......... 91%  161M 2s
 67000K .......... .......... .......... .......... .......... 91%  196M 2s
 67050K ....

 71800K .......... .......... .......... .......... .......... 97% 52.5M 1s
 71850K .......... .......... .......... .......... .......... 97% 40.2M 1s
 71900K .......... .......... .......... .......... .......... 97% 31.7M 1s
 71950K .......... .......... .......... .......... .......... 97% 48.0M 1s
 72000K .......... .......... .......... .......... .......... 97% 73.5M 1s
 72050K .......... .......... .......... .......... .......... 97% 62.7M 0s
 72100K .......... .......... .......... .......... .......... 98%  247K 0s
 72150K .......... .......... .......... .......... .......... 98% 46.4M 0s
 72200K .......... .......... .......... .......... .......... 98% 50.7M 0s
 72250K .......... .......... .......... .......... .......... 98% 39.1M 0s
 72300K .......... .......... .......... .......... .......... 98% 38.0M 0s
 72350K .......... .......... .......... .......... .......... 98% 45.8M 0s
 72400K .......... .......... .......... .......... .......... 98% 43.7M 0s
 72450K ....

  3200K .......... .......... .......... .......... ..........  4% 39.8M 24s
  3250K .......... .......... .......... .......... ..........  4% 58.8M 23s
  3300K .......... .......... .......... .......... ..........  4% 47.7M 23s
  3350K .......... .......... .......... .......... ..........  4% 69.8M 23s
  3400K .......... .......... .......... .......... ..........  4% 55.0M 22s
  3450K .......... .......... .......... .......... ..........  4%  248K 26s
  3500K .......... .......... .......... .......... ..........  4% 90.7M 26s
  3550K .......... .......... .......... .......... ..........  4%  105M 25s
  3600K .......... .......... .......... .......... ..........  4%  107M 25s
  3650K .......... .......... .......... .......... ..........  5%  109M 24s
  3700K .......... .......... .......... .......... ..........  5%  116M 24s
  3750K .......... .......... .......... .......... ..........  5%  109M 24s
  3800K .......... .......... .......... .......... ..........  5%  110M 24s

  8550K .......... .......... .......... .......... .......... 11% 34.5M 21s
  8600K .......... .......... .......... .......... .......... 11% 27.4M 21s
  8650K .......... .......... .......... .......... .......... 11% 25.2M 21s
  8700K .......... .......... .......... .......... .......... 11% 30.1M 21s
  8750K .......... .......... .......... .......... .......... 11%  247K 22s
  8800K .......... .......... .......... .......... .......... 12% 43.8M 22s
  8850K .......... .......... .......... .......... .......... 12% 37.8M 22s
  8900K .......... .......... .......... .......... .......... 12% 40.2M 22s
  8950K .......... .......... .......... .......... .......... 12% 50.3M 22s
  9000K .......... .......... .......... .......... .......... 12% 48.9M 22s
  9050K .......... .......... .......... .......... .......... 12% 33.7M 22s
  9100K .......... .......... .......... .......... .......... 12% 53.0M 21s
  9150K .......... .......... .......... .......... .......... 12% 55.8M 21s

 13900K .......... .......... .......... .......... .......... 18% 35.3M 20s
 13950K .......... .......... .......... .......... .......... 19% 31.9M 19s
 14000K .......... .......... .......... .......... .......... 19% 25.5M 19s
 14050K .......... .......... .......... .......... .......... 19% 67.2M 19s
 14100K .......... .......... .......... .......... .......... 19% 15.2M 19s
 14150K .......... .......... .......... .......... .......... 19%  249K 20s
 14200K .......... .......... .......... .......... .......... 19%  233M 20s
 14250K .......... .......... .......... .......... .......... 19%  244M 20s
 14300K .......... .......... .......... .......... .......... 19%  404M 20s
 14350K .......... .......... .......... .......... .......... 19%  218M 20s
 14400K .......... .......... .......... .......... .......... 19%  263M 20s
 14450K .......... .......... .......... .......... .......... 19%  148M 19s
 14500K .......... .......... .......... .......... .......... 19%  130M 19s

 19250K .......... .......... .......... .......... .......... 26%  166M 18s
 19300K .......... .......... .......... .......... .......... 26%  211M 18s
 19350K .......... .......... .......... .......... .......... 26% 97.2M 18s
 19400K .......... .......... .......... .......... .......... 26%  135M 18s
 19450K .......... .......... .......... .......... .......... 26%  247K 18s
 19500K .......... .......... .......... .......... .......... 26% 36.9M 18s
 19550K .......... .......... .......... .......... .......... 26% 45.3M 18s
 19600K .......... .......... .......... .......... .......... 26% 55.2M 18s
 19650K .......... .......... .......... .......... .......... 26% 34.4M 18s
 19700K .......... .......... .......... .......... .......... 26% 32.4M 18s
 19750K .......... .......... .......... .......... .......... 26% 48.4M 18s
 19800K .......... .......... .......... .......... .......... 26% 64.8M 18s
 19850K .......... .......... .......... .......... .......... 27% 41.9M 18s

 24600K .......... .......... .......... .......... .......... 33% 55.2M 16s
 24650K .......... .......... .......... .......... .......... 33% 46.0M 16s
 24700K .......... .......... .......... .......... .......... 33% 36.0M 16s
 24750K .......... .......... .......... .......... .......... 33% 35.9M 16s
 24800K .......... .......... .......... .......... .......... 33% 38.9M 16s
 24850K .......... .......... .......... .......... .......... 33%  246K 16s
 24900K .......... .......... .......... .......... .......... 33% 59.3M 16s
 24950K .......... .......... .......... .......... .......... 33% 51.7M 16s
 25000K .......... .......... .......... .......... .......... 34% 53.9M 16s
 25050K .......... .......... .......... .......... .......... 34% 77.3M 16s
 25100K .......... .......... .......... .......... .......... 34% 58.0M 16s
 25150K .......... .......... .......... .......... .......... 34% 34.0M 16s
 25200K .......... .......... .......... .......... .......... 34% 25.0M 16s

 29950K .......... .......... .......... .......... .......... 40% 51.4M 14s
 30000K .......... .......... .......... .......... .......... 40% 17.7M 14s
 30050K .......... .......... .......... .......... .......... 40% 41.2M 14s
 30100K .......... .......... .......... .......... .......... 40% 42.5M 14s
 30150K .......... .......... .......... .......... .......... 41%  245K 14s
 30200K .......... .......... .......... .......... .......... 41% 35.1M 14s
 30250K .......... .......... .......... .......... .......... 41% 56.8M 14s
 30300K .......... .......... .......... .......... .......... 41% 31.9M 14s
 30350K .......... .......... .......... .......... .......... 41% 58.5M 14s
 30400K .......... .......... .......... .......... .......... 41% 36.7M 14s
 30450K .......... .......... .......... .......... .......... 41% 35.0M 14s
 30500K .......... .......... .......... .......... .......... 41% 28.2M 14s
 30550K .......... .......... .......... .......... .......... 41% 45.7M 14s

 35300K .......... .......... .......... .......... .......... 48% 40.8M 12s
 35350K .......... .......... .......... .......... .......... 48% 62.4M 12s
 35400K .......... .......... .......... .......... .......... 48% 54.6M 12s
 35450K .......... .......... .......... .......... .......... 48%  245K 13s
 35500K .......... .......... .......... .......... .......... 48% 33.8M 13s
 35550K .......... .......... .......... .......... .......... 48% 42.8M 13s
 35600K .......... .......... .......... .......... .......... 48% 38.3M 12s
 35650K .......... .......... .......... .......... .......... 48% 43.1M 12s
 35700K .......... .......... .......... .......... .......... 48% 31.1M 12s
 35750K .......... .......... .......... .......... .......... 48% 30.2M 12s
 35800K .......... .......... .......... .......... .......... 48% 25.7M 12s
 35850K .......... .......... .......... .......... .......... 48% 46.5M 12s
 35900K .......... .......... .......... .......... .......... 48% 40.6M 12s

 40650K .......... .......... .......... .......... .......... 55% 73.2M 11s
 40700K .......... .......... .......... .......... .......... 55% 78.2M 11s
 40750K .......... .......... .......... .......... .......... 55% 69.0M 11s
 40800K .......... .......... .......... .......... .......... 55%  248K 11s
 40850K .......... .......... .......... .......... .......... 55% 34.8M 11s
 40900K .......... .......... .......... .......... .......... 55% 56.6M 11s
 40950K .......... .......... .......... .......... .......... 55% 48.0M 11s
 41000K .......... .......... .......... .......... .......... 55% 30.6M 11s
 41050K .......... .......... .......... .......... .......... 55% 42.6M 11s
 41100K .......... .......... .......... .......... .......... 55% 52.0M 11s
 41150K .......... .......... .......... .......... .......... 55% 51.7M 11s
 41200K .......... .......... .......... .......... .......... 56% 40.2M 11s
 41250K .......... .......... .......... .......... .......... 56% 32.8M 11s

 46000K .......... .......... .......... .......... .......... 62% 33.3M 9s
 46050K .......... .......... .......... .......... .......... 62% 50.0M 9s
 46100K .......... .......... .......... .......... .......... 62%  245K 9s
 46150K .......... .......... .......... .......... .......... 62% 48.9M 9s
 46200K .......... .......... .......... .......... .......... 62% 43.1M 9s
 46250K .......... .......... .......... .......... .......... 62% 54.1M 9s
 46300K .......... .......... .......... .......... .......... 62% 43.0M 9s
 46350K .......... .......... .......... .......... .......... 63% 30.4M 9s
 46400K .......... .......... .......... .......... .......... 63% 24.6M 9s
 46450K .......... .......... .......... .......... .......... 63% 47.3M 9s
 46500K .......... .......... .......... .......... .......... 63% 49.3M 9s
 46550K .......... .......... .......... .......... .......... 63% 57.4M 9s
 46600K .......... .......... .......... .......... .......... 63% 46.2M 9s
 46650K ....

 51400K .......... .......... .......... .......... .......... 69% 43.7M 7s
 51450K .......... .......... .......... .......... .......... 69%  247K 7s
 51500K .......... .......... .......... .......... .......... 70% 39.6M 7s
 51550K .......... .......... .......... .......... .......... 70% 37.6M 7s
 51600K .......... .......... .......... .......... .......... 70% 33.4M 7s
 51650K .......... .......... .......... .......... .......... 70% 36.3M 7s
 51700K .......... .......... .......... .......... .......... 70% 26.2M 7s
 51750K .......... .......... .......... .......... .......... 70% 43.1M 7s
 51800K .......... .......... .......... .......... .......... 70% 35.5M 7s
 51850K .......... .......... .......... .......... .......... 70% 25.1M 7s
 51900K .......... .......... .......... .......... .......... 70% 17.1M 7s
 51950K .......... .......... .......... .......... .......... 70% 24.6M 7s
 52000K .......... .......... .......... .......... .......... 70% 28.2M 7s
 52050K ....

 56800K .......... .......... .......... .......... .......... 77% 40.7M 5s
 56850K .......... .......... .......... .......... .......... 77%  246K 5s
 56900K .......... .......... .......... .......... .......... 77%  174M 5s
 56950K .......... .......... .......... .......... .......... 77%  238M 5s
 57000K .......... .......... .......... .......... .......... 77%  214M 5s
 57050K .......... .......... .......... .......... .......... 77%  343M 5s
 57100K .......... .......... .......... .......... .......... 77%  166M 5s
 57150K .......... .......... .......... .......... .......... 77%  147M 5s
 57200K .......... .......... .......... .......... .......... 77%  204M 5s
 57250K .......... .......... .......... .......... .......... 77%  155M 5s
 57300K .......... .......... .......... .......... .......... 77%  204M 5s
 57350K .......... .......... .......... .......... .......... 77%  252M 5s
 57400K .......... .......... .......... .......... .......... 78%  214M 5s
 57450K ....

 62200K .......... .......... .......... .......... .......... 84% 56.2M 4s
 62250K .......... .......... .......... .......... .......... 84% 41.9M 4s
 62300K .......... .......... .......... .......... .......... 84% 38.9M 4s
 62350K .......... .......... .......... .......... .......... 84% 56.0M 4s
 62400K .......... .......... .......... .......... .......... 84% 47.0M 4s
 62450K .......... .......... .......... .......... .......... 84% 49.9M 4s
 62500K .......... .......... .......... .......... .......... 84% 35.7M 4s
 62550K .......... .......... .......... .......... .......... 85% 40.3M 4s
 62600K .......... .......... .......... .......... .......... 85% 36.3M 4s
 62650K .......... .......... .......... .......... .......... 85% 52.5M 4s
 62700K .......... .......... .......... .......... .......... 85% 17.0M 4s
 62750K .......... .......... .......... .......... .......... 85%  247K 4s
 62800K .......... .......... .......... .......... .......... 85% 36.2M 4s
 62850K ....

 67600K .......... .......... .......... .......... .......... 91% 27.0M 2s
 67650K .......... .......... .......... .......... .......... 91% 39.5M 2s
 67700K .......... .......... .......... .......... .......... 92% 30.9M 2s
 67750K .......... .......... .......... .......... .......... 92% 26.0M 2s
 67800K .......... .......... .......... .......... .......... 92% 31.4M 2s
 67850K .......... .......... .......... .......... .......... 92% 22.1M 2s
 67900K .......... .......... .......... .......... .......... 92% 30.3M 2s
 67950K .......... .......... .......... .......... .......... 92% 37.9M 2s
 68000K .......... .......... .......... .......... .......... 92% 44.1M 2s
 68050K .......... .......... .......... .......... .......... 92%  248K 2s
 68100K .......... .......... .......... .......... .......... 92% 35.1M 2s
 68150K .......... .......... .......... .......... .......... 92% 45.6M 2s
 68200K .......... .......... .......... .......... .......... 92% 50.3M 2s
 68250K ....

 73000K .......... .......... .......... .......... .......... 99% 38.0M 0s
 73050K .......... .......... .......... .......... .......... 99% 19.8M 0s
 73100K .......... .......... .......... .......... .......... 99% 45.4M 0s
 73150K .......... .......... .......... .......... .......... 99% 41.8M 0s
 73200K .......... .......... .......... .......... .......... 99% 36.7M 0s
 73250K .......... .......... .......... .......... .......... 99% 38.0M 0s
 73300K .......... .......... .......... .......... .......... 99% 31.7M 0s
 73350K .......... .......... .......... .......... .......... 99% 25.9M 0s
 73400K .......... .......... .......... .......... .......... 99% 32.8M 0s
 73450K .......... .......... .......... .......... .......... 99%  246K 0s
 73500K .......... .......... .......... .......... .......... 99% 48.4M 0s
 73550K .......... .......... .......... .......... .......... 99% 46.8M 0s
 73600K .......... ......                                     100% 57.2M=24s

2022-06-10

  4400K .......... .......... .......... .......... ..........  5% 51.6M 24s
  4450K .......... .......... .......... .......... ..........  5% 81.2M 24s
  4500K .......... .......... .......... .......... ..........  5%  107M 23s
  4550K .......... .......... .......... .......... ..........  6% 53.1M 23s
  4600K .......... .......... .......... .......... ..........  6% 57.8M 23s
  4650K .......... .......... .......... .......... ..........  6%  244K 26s
  4700K .......... .......... .......... .......... ..........  6% 42.1M 25s
  4750K .......... .......... .......... .......... ..........  6% 38.9M 25s
  4800K .......... .......... .......... .......... ..........  6% 55.7M 25s
  4850K .......... .......... .......... .......... ..........  6% 35.6M 25s
  4900K .......... .......... .......... .......... ..........  6% 34.0M 24s
  4950K .......... .......... .......... .......... ..........  6% 32.2M 24s
  5000K .......... .......... .......... .......... ..........  6% 26.5M 24s

  9750K .......... .......... .......... .......... .......... 12% 34.5M 22s
  9800K .......... .......... .......... .......... .......... 12% 73.0M 22s
  9850K .......... .......... .......... .......... .......... 13% 73.3M 21s
  9900K .......... .......... .......... .......... .......... 13%  249K 23s
  9950K .......... .......... .......... .......... .......... 13%  189M 22s
 10000K .......... .......... .......... .......... .......... 13%  197M 22s
 10050K .......... .......... .......... .......... .......... 13%  212M 22s
 10100K .......... .......... .......... .......... .......... 13%  182M 22s
 10150K .......... .......... .......... .......... .......... 13%  179M 22s
 10200K .......... .......... .......... .......... .......... 13%  147M 22s
 10250K .......... .......... .......... .......... .......... 13%  230M 22s
 10300K .......... .......... .......... .......... .......... 13%  186M 22s
 10350K .......... .......... .......... .......... .......... 13%  173M 21s

 15100K .......... .......... .......... .......... .......... 19% 94.6M 20s
 15150K .......... .......... .......... .......... .......... 20% 48.2M 20s
 15200K .......... .......... .......... .......... .......... 20% 67.9M 20s
 15250K .......... .......... .......... .......... .......... 20% 52.1M 20s
 15300K .......... .......... .......... .......... .......... 20% 55.3M 20s
 15350K .......... .......... .......... .......... .......... 20% 65.2M 20s
 15400K .......... .......... .......... .......... .......... 20% 88.0M 20s
 15450K .......... .......... .......... .......... .......... 20% 66.6M 20s
 15500K .......... .......... .......... .......... .......... 20% 63.4M 20s
 15550K .......... .......... .......... .......... .......... 20% 64.6M 20s
 15600K .......... .......... .......... .......... .......... 20% 51.7M 20s
 15650K .......... .......... .......... .......... .......... 20% 65.6M 20s
 15700K .......... .......... .......... .......... .......... 20%  247K 20s

 20450K .......... .......... .......... .......... .......... 26% 40.3M 18s
 20500K .......... .......... .......... .......... .......... 27% 59.8M 18s
 20550K .......... .......... .......... .......... .......... 27% 52.0M 18s
 20600K .......... .......... .......... .......... .......... 27% 19.8M 18s
 20650K .......... .......... .......... .......... .......... 27% 35.8M 18s
 20700K .......... .......... .......... .......... .......... 27% 56.7M 18s
 20750K .......... .......... .......... .......... .......... 27% 34.2M 18s
 20800K .......... .......... .......... .......... .......... 27% 75.9M 18s
 20850K .......... .......... .......... .......... .......... 27% 69.8M 18s
 20900K .......... .......... .......... .......... .......... 27% 86.4M 18s
 20950K .......... .......... .......... .......... .......... 27%  246K 18s
 21000K .......... .......... .......... .......... .......... 27% 43.2M 18s
 21050K .......... .......... .......... .......... .......... 27% 36.2M 18s

 25800K .......... .......... .......... .......... .......... 34% 59.5M 16s
 25850K .......... .......... .......... .......... .......... 34% 34.0M 16s
 25900K .......... .......... .......... .......... .......... 34% 29.2M 16s
 25950K .......... .......... .......... .......... .......... 34% 28.9M 16s
 26000K .......... .......... .......... .......... .......... 34% 28.4M 16s
 26050K .......... .......... .......... .......... .......... 34% 35.5M 16s
 26100K .......... .......... .......... .......... .......... 34% 46.7M 16s
 26150K .......... .......... .......... .......... .......... 34% 34.3M 16s
 26200K .......... .......... .......... .......... .......... 34% 52.3M 16s
 26250K .......... .......... .......... .......... .......... 34%  246K 16s
 26300K .......... .......... .......... .......... .......... 34%  266M 16s
 26350K .......... .......... .......... .......... .......... 34%  509M 16s
 26400K .......... .......... .......... .......... .......... 34%  339M 16s

 31150K .......... .......... .......... .......... .......... 41% 45.2M 15s
 31200K .......... .......... .......... .......... .......... 41% 47.4M 15s
 31250K .......... .......... .......... .......... .......... 41% 30.3M 15s
 31300K .......... .......... .......... .......... .......... 41% 23.3M 15s
 31350K .......... .......... .......... .......... .......... 41% 39.8M 15s
 31400K .......... .......... .......... .......... .......... 41% 34.5M 15s
 31450K .......... .......... .......... .......... .......... 41% 32.5M 14s
 31500K .......... .......... .......... .......... .......... 41% 25.5M 14s
 31550K .......... .......... .......... .......... .......... 41% 38.2M 14s
 31600K .......... .......... .......... .......... .......... 41% 31.3M 14s
 31650K .......... .......... .......... .......... .......... 41%  246K 15s
 31700K .......... .......... .......... .......... .......... 41% 36.1M 15s
 31750K .......... .......... .......... .......... .......... 41% 52.3M 15s

 36500K .......... .......... .......... .......... .......... 48% 43.5M 13s
 36550K .......... .......... .......... .......... .......... 48% 41.1M 13s
 36600K .......... .......... .......... .......... .......... 48% 32.2M 13s
 36650K .......... .......... .......... .......... .......... 48% 53.7M 13s
 36700K .......... .......... .......... .......... .......... 48% 39.5M 13s
 36750K .......... .......... .......... .......... .......... 48% 23.0M 13s
 36800K .......... .......... .......... .......... .......... 48% 37.6M 13s
 36850K .......... .......... .......... .......... .......... 48% 15.2M 13s
 36900K .......... .......... .......... .......... .......... 48% 42.7M 13s
 36950K .......... .......... .......... .......... .......... 48% 33.3M 13s
 37000K .......... .......... .......... .......... .......... 48% 32.9M 13s
 37050K .......... .......... .......... .......... .......... 48%  248K 13s
 37100K .......... .......... .......... .......... .......... 48%  174M 13s

 41850K .......... .......... .......... .......... .......... 55% 30.5M 11s
 41900K .......... .......... .......... .......... .......... 55% 32.7M 11s
 41950K .......... .......... .......... .......... .......... 55% 44.3M 11s
 42000K .......... .......... .......... .......... .......... 55% 39.2M 11s
 42050K .......... .......... .......... .......... .......... 55% 31.3M 11s
 42100K .......... .......... .......... .......... .......... 55% 32.7M 11s
 42150K .......... .......... .......... .......... .......... 55% 24.4M 11s
 42200K .......... .......... .......... .......... .......... 55% 36.7M 11s
 42250K .......... .......... .......... .......... .......... 55% 63.3M 11s
 42300K .......... .......... .......... .......... .......... 55% 54.6M 11s
 42350K .......... .......... .......... .......... .......... 55%  246K 11s
 42400K .......... .......... .......... .......... .......... 55% 71.7M 11s
 42450K .......... .......... .......... .......... .......... 55% 53.8M 11s

 47200K .......... .......... .......... .......... .......... 62% 46.3M 9s
 47250K .......... .......... .......... .......... .......... 62% 79.0M 9s
 47300K .......... .......... .......... .......... .......... 62% 45.4M 9s
 47350K .......... .......... .......... .......... .......... 62% 25.4M 9s
 47400K .......... .......... .......... .......... .......... 62% 39.5M 9s
 47450K .......... .......... .......... .......... .......... 62% 37.9M 9s
 47500K .......... .......... .......... .......... .......... 62% 52.9M 9s
 47550K .......... .......... .......... .......... .......... 62% 30.7M 9s
 47600K .......... .......... .......... .......... .......... 62%  245K 9s
 47650K .......... .......... .......... .......... .......... 62% 31.4M 9s
 47700K .......... .......... .......... .......... .......... 62% 34.2M 9s
 47750K .......... .......... .......... .......... .......... 62% 43.1M 9s
 47800K .......... .......... .......... .......... .......... 63% 21.9M 9s
 47850K ....

 52600K .......... .......... .......... .......... .......... 69% 31.6M 8s
 52650K .......... .......... .......... .......... .......... 69% 49.4M 8s
 52700K .......... .......... .......... .......... .......... 69% 75.2M 8s
 52750K .......... .......... .......... .......... .......... 69% 44.2M 8s
 52800K .......... .......... .......... .......... .......... 69% 45.2M 8s
 52850K .......... .......... .......... .......... .......... 69% 86.7M 7s
 52900K .......... .......... .......... .......... .......... 69% 56.8M 7s
 52950K .......... .......... .......... .......... .......... 69%  247K 8s
 53000K .......... .......... .......... .......... .......... 69% 38.8M 8s
 53050K .......... .......... .......... .......... .......... 69% 49.9M 7s
 53100K .......... .......... .......... .......... .......... 69% 32.4M 7s
 53150K .......... .......... .......... .......... .......... 70% 31.4M 7s
 53200K .......... .......... .......... .......... .......... 70% 49.6M 7s
 53250K ....

 58000K .......... .......... .......... .......... .......... 76% 38.3M 6s
 58050K .......... .......... .......... .......... .......... 76% 40.1M 6s
 58100K .......... .......... .......... .......... .......... 76% 24.0M 6s
 58150K .......... .......... .......... .......... .......... 76% 45.2M 6s
 58200K .......... .......... .......... .......... .......... 76% 68.4M 6s
 58250K .......... .......... .......... .......... .......... 76% 86.4M 6s
 58300K .......... .......... .......... .......... .......... 76%  247K 6s
 58350K .......... .......... .......... .......... .......... 76% 32.4M 6s
 58400K .......... .......... .......... .......... .......... 76% 16.2M 6s
 58450K .......... .......... .......... .......... .......... 77% 48.3M 6s
 58500K .......... .......... .......... .......... .......... 77% 56.6M 6s
 58550K .......... .......... .......... .......... .......... 77% 37.9M 6s
 58600K .......... .......... .......... .......... .......... 77% 48.0M 6s
 58650K ....

 63400K .......... .......... .......... .......... .......... 83% 34.2M 4s
 63450K .......... .......... .......... .......... .......... 83% 55.3M 4s
 63500K .......... .......... .......... .......... .......... 83% 50.5M 4s
 63550K .......... .......... .......... .......... .......... 83% 40.9M 4s
 63600K .......... .......... .......... .......... .......... 83% 42.7M 4s
 63650K .......... .......... .......... .......... .......... 83%  244K 4s
 63700K .......... .......... .......... .......... .......... 83% 36.8M 4s
 63750K .......... .......... .......... .......... .......... 84% 40.8M 4s
 63800K .......... .......... .......... .......... .......... 84% 43.1M 4s
 63850K .......... .......... .......... .......... .......... 84% 56.6M 4s
 63900K .......... .......... .......... .......... .......... 84% 48.7M 4s
 63950K .......... .......... .......... .......... .......... 84% 48.9M 4s
 64000K .......... .......... .......... .......... .......... 84% 45.2M 4s
 64050K ....

 68800K .......... .......... .......... .......... .......... 90% 57.6M 2s
 68850K .......... .......... .......... .......... .......... 90% 74.1M 2s
 68900K .......... .......... .......... .......... .......... 90% 23.3M 2s
 68950K .......... .......... .......... .......... .......... 90% 33.2M 2s
 69000K .......... .......... .......... .......... .......... 90%  245K 2s
 69050K .......... .......... .......... .......... .......... 90% 40.0M 2s
 69100K .......... .......... .......... .......... .......... 91% 62.9M 2s
 69150K .......... .......... .......... .......... .......... 91% 36.5M 2s
 69200K .......... .......... .......... .......... .......... 91% 38.7M 2s
 69250K .......... .......... .......... .......... .......... 91% 46.3M 2s
 69300K .......... .......... .......... .......... .......... 91% 44.3M 2s
 69350K .......... .......... .......... .......... .......... 91% 54.6M 2s
 69400K .......... .......... .......... .......... .......... 91% 60.8M 2s
 69450K ....

 74200K .......... .......... .......... .......... .......... 97%  232M 1s
 74250K .......... .......... .......... .......... .......... 97%  351M 1s
 74300K .......... .......... .......... .......... .......... 97%  246K 1s
 74350K .......... .......... .......... .......... .......... 97% 52.6M 1s
 74400K .......... .......... .......... .......... .......... 98% 56.8M 0s
 74450K .......... .......... .......... .......... .......... 98% 52.5M 0s
 74500K .......... .......... .......... .......... .......... 98% 51.5M 0s
 74550K .......... .......... .......... .......... .......... 98% 42.3M 0s
 74600K .......... .......... .......... .......... .......... 98% 58.7M 0s
 74650K .......... .......... .......... .......... .......... 98% 49.4M 0s
 74700K .......... .......... .......... .......... .......... 98% 61.4M 0s
 74750K .......... .......... .......... .......... .......... 98% 57.9M 0s
 74800K .......... .......... .......... .......... .......... 98% 59.0M 0s
 74850K ....

  3300K .......... .......... .......... .......... ..........  4% 73.8M 23s
  3350K .......... .......... .......... .......... ..........  4%  247K 27s
  3400K .......... .......... .......... .......... ..........  4% 43.3M 26s
  3450K .......... .......... .......... .......... ..........  4% 62.2M 26s
  3500K .......... .......... .......... .......... ..........  4% 57.7M 26s
  3550K .......... .......... .......... .......... ..........  4% 42.8M 25s
  3600K .......... .......... .......... .......... ..........  4% 43.9M 25s
  3650K .......... .......... .......... .......... ..........  4% 50.5M 25s
  3700K .......... .......... .......... .......... ..........  4% 72.6M 24s
  3750K .......... .......... .......... .......... ..........  5% 16.4M 24s
  3800K .......... .......... .......... .......... ..........  5% 38.9M 24s
  3850K .......... .......... .......... .......... ..........  5% 30.8M 23s
  3900K .......... .......... .......... .......... ..........  5% 32.6M 23s

  8650K .......... .......... .......... .......... .......... 11% 56.7M 23s
  8700K .......... .......... .......... .......... .......... 11% 43.2M 23s
  8750K .......... .......... .......... .......... .......... 11% 56.1M 23s
  8800K .......... .......... .......... .......... .......... 11% 46.1M 23s
  8850K .......... .......... .......... .......... .......... 11% 51.7M 22s
  8900K .......... .......... .......... .......... .......... 11% 77.2M 22s
  8950K .......... .......... .......... .......... .......... 11% 45.3M 22s
  9000K .......... .......... .......... .......... .......... 11% 60.3M 22s
  9050K .......... .......... .......... .......... .......... 11% 53.0M 22s
  9100K .......... .......... .......... .......... .......... 12% 64.1M 22s
  9150K .......... .......... .......... .......... .......... 12% 45.3M 22s
  9200K .......... .......... .......... .......... .......... 12% 28.6M 21s
  9250K .......... .......... .......... .......... .......... 12%  247K 23s

 14000K .......... .......... .......... .......... .......... 18%  158M 21s
 14050K .......... .......... .......... .......... .......... 18%  209M 21s
 14100K .......... .......... .......... .......... .......... 18%  199M 20s
 14150K .......... .......... .......... .......... .......... 18%  233M 20s
 14200K .......... .......... .......... .......... .......... 18%  185M 20s
 14250K .......... .......... .......... .......... .......... 18%  140M 20s
 14300K .......... .......... .......... .......... .......... 18%  175M 20s
 14350K .......... .......... .......... .......... .......... 18%  173M 20s
 14400K .......... .......... .......... .......... .......... 19%  150M 20s
 14450K .......... .......... .......... .......... .......... 19%  210M 20s
 14500K .......... .......... .......... .......... .......... 19%  246K 21s
 14550K .......... .......... .......... .......... .......... 19% 44.5M 21s
 14600K .......... .......... .......... .......... .......... 19% 67.6M 20s

 19350K .......... .......... .......... .......... .......... 25% 35.7M 19s
 19400K .......... .......... .......... .......... .......... 25% 63.6M 19s
 19450K .......... .......... .......... .......... .......... 25% 49.4M 19s
 19500K .......... .......... .......... .......... .......... 25% 27.9M 18s
 19550K .......... .......... .......... .......... .......... 25% 43.0M 18s
 19600K .......... .......... .......... .......... .......... 25% 50.9M 18s
 19650K .......... .......... .......... .......... .......... 25% 35.8M 18s
 19700K .......... .......... .......... .......... .......... 26% 28.9M 18s
 19750K .......... .......... .......... .......... .......... 26% 74.3M 18s
 19800K .......... .......... .......... .......... .......... 26% 41.7M 18s
 19850K .......... .......... .......... .......... .......... 26%  246K 19s
 19900K .......... .......... .......... .......... .......... 26% 41.6M 19s
 19950K .......... .......... .......... .......... .......... 26% 42.9M 19s

 24700K .......... .......... .......... .......... .......... 32% 43.5M 17s
 24750K .......... .......... .......... .......... .......... 32% 30.0M 17s
 24800K .......... .......... .......... .......... .......... 32% 24.8M 17s
 24850K .......... .......... .......... .......... .......... 32% 40.7M 17s
 24900K .......... .......... .......... .......... .......... 32% 50.1M 17s
 24950K .......... .......... .......... .......... .......... 32% 55.1M 17s
 25000K .......... .......... .......... .......... .......... 32% 54.9M 17s
 25050K .......... .......... .......... .......... .......... 33% 47.9M 17s
 25100K .......... .......... .......... .......... .......... 33% 33.3M 17s
 25150K .......... .......... .......... .......... .......... 33% 29.8M 16s
 25200K .......... .......... .......... .......... .......... 33% 25.8M 16s
 25250K .......... .......... .......... .......... .......... 33%  245K 17s
 25300K .......... .......... .......... .......... .......... 33% 40.0M 17s

 30050K .......... .......... .......... .......... .......... 39% 56.4M 15s
 30100K .......... .......... .......... .......... .......... 39% 44.4M 15s
 30150K .......... .......... .......... .......... .......... 39% 51.2M 15s
 30200K .......... .......... .......... .......... .......... 39% 52.0M 15s
 30250K .......... .......... .......... .......... .......... 39% 53.6M 15s
 30300K .......... .......... .......... .......... .......... 39% 43.0M 15s
 30350K .......... .......... .......... .......... .......... 40% 46.5M 15s
 30400K .......... .......... .......... .......... .......... 40% 34.2M 15s
 30450K .......... .......... .......... .......... .......... 40% 35.8M 15s
 30500K .......... .......... .......... .......... .......... 40% 38.6M 15s
 30550K .......... .......... .......... .......... .......... 40% 36.9M 15s
 30600K .......... .......... .......... .......... .......... 40% 36.7M 15s
 30650K .......... .......... .......... .......... .......... 40%  246K 15s

 35400K .......... .......... .......... .......... .......... 46%  246K 13s
 35450K .......... .......... .......... .......... .......... 46% 35.1M 13s
 35500K .......... .......... .......... .......... .......... 46% 45.8M 13s
 35550K .......... .......... .......... .......... .......... 46% 48.8M 13s
 35600K .......... .......... .......... .......... .......... 46% 36.4M 13s
 35650K .......... .......... .......... .......... .......... 47% 29.0M 13s
 35700K .......... .......... .......... .......... .......... 47% 43.0M 13s
 35750K .......... .......... .......... .......... .......... 47% 39.7M 13s
 35800K .......... .......... .......... .......... .......... 47% 52.8M 13s
 35850K .......... .......... .......... .......... .......... 47% 78.8M 13s
 35900K .......... .......... .......... .......... .......... 47% 22.0M 13s
 35950K .......... .......... .......... .......... .......... 47% 33.0M 13s
 36000K .......... .......... .......... .......... .......... 47% 77.5M 13s

 40750K .......... .......... .......... .......... .......... 53% 43.5M 12s
 40800K .......... .......... .......... .......... .......... 53% 37.4M 12s
 40850K .......... .......... .......... .......... .......... 53% 27.6M 11s
 40900K .......... .......... .......... .......... .......... 53% 27.1M 11s
 40950K .......... .......... .......... .......... .......... 53% 36.9M 11s
 41000K .......... .......... .......... .......... .......... 54% 36.2M 11s
 41050K .......... .......... .......... .......... .......... 54% 28.3M 11s
 41100K .......... .......... .......... .......... .......... 54% 44.3M 11s
 41150K .......... .......... .......... .......... .......... 54% 28.5M 11s
 41200K .......... .......... .......... .......... .......... 54% 32.4M 11s
 41250K .......... .......... .......... .......... .......... 54% 35.4M 11s
 41300K .......... .......... .......... .......... .......... 54% 33.2M 11s
 41350K .......... .......... .......... .......... .......... 54% 19.5M 11s

 46100K .......... .......... .......... .......... .......... 60% 49.3M 10s
 46150K .......... .......... .......... .......... .......... 60% 48.0M 10s
 46200K .......... .......... .......... .......... .......... 60% 46.9M 10s
 46250K .......... .......... .......... .......... .......... 60% 39.0M 10s
 46300K .......... .......... .......... .......... .......... 61% 55.7M 10s
 46350K .......... .......... .......... .......... .......... 61% 53.5M 10s
 46400K .......... .......... .......... .......... .......... 61% 36.7M 10s
 46450K .......... .......... .......... .......... .......... 61% 59.7M 10s
 46500K .......... .......... .......... .......... .......... 61% 51.1M 10s
 46550K .......... .......... .......... .......... .......... 61% 58.8M 10s
 46600K .......... .......... .......... .......... .......... 61% 67.0M 10s
 46650K .......... .......... .......... .......... .......... 61%  246K 10s
 46700K .......... .......... .......... .......... .......... 61% 45.0M 10s

 51500K .......... .......... .......... .......... .......... 67%  117M 8s
 51550K .......... .......... .......... .......... .......... 67% 94.5M 8s
 51600K .......... .......... .......... .......... .......... 68%  121M 8s
 51650K .......... .......... .......... .......... .......... 68% 95.0M 8s
 51700K .......... .......... .......... .......... .......... 68%  116M 8s
 51750K .......... .......... .......... .......... .......... 68%  112M 8s
 51800K .......... .......... .......... .......... .......... 68%  144M 8s
 51850K .......... .......... .......... .......... .......... 68%  115M 8s
 51900K .......... .......... .......... .......... .......... 68%  247K 8s
 51950K .......... .......... .......... .......... .......... 68% 37.2M 8s
 52000K .......... .......... .......... .......... .......... 68% 32.7M 8s
 52050K .......... .......... .......... .......... .......... 68% 48.1M 8s
 52100K .......... .......... .......... .......... .......... 68% 12.5M 8s
 52150K ....

 56900K .......... .......... .......... .......... .......... 74% 16.8M 6s
 56950K .......... .......... .......... .......... .......... 75% 31.6M 6s
 57000K .......... .......... .......... .......... .......... 75% 57.2M 6s
 57050K .......... .......... .......... .......... .......... 75% 55.8M 6s
 57100K .......... .......... .......... .......... .......... 75% 32.5M 6s
 57150K .......... .......... .......... .......... .......... 75% 35.2M 6s
 57200K .......... .......... .......... .......... .......... 75% 24.3M 6s
 57250K .......... .......... .......... .......... .......... 75%  246K 6s
 57300K .......... .......... .......... .......... .......... 75% 31.4M 6s
 57350K .......... .......... .......... .......... .......... 75% 44.4M 6s
 57400K .......... .......... .......... .......... .......... 75% 22.8M 6s
 57450K .......... .......... .......... .......... .......... 75% 35.1M 6s
 57500K .......... .......... .......... .......... .......... 75% 49.0M 6s
 57550K ....

 62300K .......... .......... .......... .......... .......... 82% 39.7M 4s
 62350K .......... .......... .......... .......... .......... 82% 68.1M 4s
 62400K .......... .......... .......... .......... .......... 82% 57.7M 4s
 62450K .......... .......... .......... .......... .......... 82% 39.8M 4s
 62500K .......... .......... .......... .......... .......... 82% 33.9M 4s
 62550K .......... .......... .......... .......... .......... 82%  246K 4s
 62600K .......... .......... .......... .......... .......... 82% 32.0M 4s
 62650K .......... .......... .......... .......... .......... 82% 30.4M 4s
 62700K .......... .......... .......... .......... .......... 82% 21.8M 4s
 62750K .......... .......... .......... .......... .......... 82% 26.9M 4s
 62800K .......... .......... .......... .......... .......... 82% 13.0M 4s
 62850K .......... .......... .......... .......... .......... 82% 23.8M 4s
 62900K .......... .......... .......... .......... .......... 82% 29.5M 4s
 62950K ....

 67700K .......... .......... .......... .......... .......... 89%  175M 3s
 67750K .......... .......... .......... .......... .......... 89%  179M 3s
 67800K .......... .......... .......... .......... .......... 89%  181M 3s
 67850K .......... .......... .......... .......... .......... 89%  207M 3s
 67900K .......... .......... .......... .......... .......... 89%  218M 3s
 67950K .......... .......... .......... .......... .......... 89%  246K 3s
 68000K .......... .......... .......... .......... .......... 89% 46.5M 3s
 68050K .......... .......... .......... .......... .......... 89% 31.9M 3s
 68100K .......... .......... .......... .......... .......... 89% 38.6M 3s
 68150K .......... .......... .......... .......... .......... 89% 44.2M 3s
 68200K .......... .......... .......... .......... .......... 89% 43.2M 3s
 68250K .......... .......... .......... .......... .......... 89% 54.8M 2s
 68300K .......... .......... .......... .......... .......... 90% 45.7M 2s
 68350K ....

 73100K .......... .......... .......... .......... .......... 96%  107M 1s
 73150K .......... .......... .......... .......... .......... 96%  115M 1s
 73200K .......... .......... .......... .......... .......... 96% 85.8M 1s
 73250K .......... .......... .......... .......... .......... 96%  126M 1s
 73300K .......... .......... .......... .......... .......... 96%  247K 1s
 73350K .......... .......... .......... .......... .......... 96% 63.4M 1s
 73400K .......... .......... .......... .......... .......... 96% 87.6M 1s
 73450K .......... .......... .......... .......... .......... 96% 61.8M 1s
 73500K .......... .......... .......... .......... .......... 96% 41.8M 1s
 73550K .......... .......... .......... .......... .......... 96% 60.3M 1s
 73600K .......... .......... .......... .......... .......... 96% 64.6M 1s
 73650K .......... .......... .......... .......... .......... 97% 48.7M 1s
 73700K .......... .......... .......... .......... .......... 97% 51.8M 1s
 73750K ....

  2200K .......... .......... .......... .......... ..........  6% 9.55M 12s
  2250K .......... .......... .......... .......... ..........  6% 12.7M 12s
  2300K .......... .......... .......... .......... ..........  6% 6.72M 12s
  2350K .......... .......... .......... .......... ..........  6% 8.55M 12s
  2400K .......... .......... .......... .......... ..........  6% 4.16M 12s
  2450K .......... .......... .......... .......... ..........  6% 2.61M 12s
  2500K .......... .......... .......... .......... ..........  7% 15.6M 11s
  2550K .......... .......... .......... .......... ..........  7% 1.46M 12s
  2600K .......... .......... .......... .......... ..........  7% 6.65M 11s
  2650K .......... .......... .......... .......... ..........  7% 8.52M 11s
  2700K .......... .......... .......... .......... ..........  7% 2.26M 11s
  2750K .......... .......... .......... .......... ..........  7% 14.7M 11s
  2800K .......... .......... .......... .......... ..........  7% 14.8M 11s

  7550K .......... .......... .......... .......... .......... 20% 85.6M 10s
  7600K .......... .......... .......... .......... .......... 21% 60.2M 9s
  7650K .......... .......... .......... .......... .......... 21% 63.8M 9s
  7700K .......... .......... .......... .......... .......... 21% 77.3M 9s
  7750K .......... .......... .......... .......... .......... 21% 69.1M 9s
  7800K .......... .......... .......... .......... .......... 21%  247K 10s
  7850K .......... .......... .......... .......... .......... 21%  292M 10s
  7900K .......... .......... .......... .......... .......... 21%  241M 10s
  7950K .......... .......... .......... .......... .......... 21%  289M 10s
  8000K .......... .......... .......... .......... .......... 22%  240M 10s
  8050K .......... .......... .......... .......... .......... 22%  208M 9s
  8100K .......... .......... .......... .......... .......... 22%  240M 9s
  8150K .......... .......... .......... .......... .......... 22%  175M 9s
  8200

 12950K .......... .......... .......... .......... .......... 35% 23.3M 8s
 13000K .......... .......... .......... .......... .......... 35% 65.7M 8s
 13050K .......... .......... .......... .......... .......... 35%  245K 8s
 13100K .......... .......... .......... .......... .......... 36% 56.9M 8s
 13150K .......... .......... .......... .......... .......... 36% 43.6M 8s
 13200K .......... .......... .......... .......... .......... 36% 38.9M 8s
 13250K .......... .......... .......... .......... .......... 36% 49.9M 8s
 13300K .......... .......... .......... .......... .......... 36% 54.0M 8s
 13350K .......... .......... .......... .......... .......... 36% 21.7M 8s
 13400K .......... .......... .......... .......... .......... 36% 35.0M 8s
 13450K .......... .......... .......... .......... .......... 37% 26.3M 8s
 13500K .......... .......... .......... .......... .......... 37% 31.7M 7s
 13550K .......... .......... .......... .......... .......... 37% 20.4M 7s
 13600K ....

 18350K .......... .......... .......... .......... .......... 50% 42.7M 6s
 18400K .......... .......... .......... .......... .......... 50%  248K 6s
 18450K .......... .......... .......... .......... .......... 50%  106M 6s
 18500K .......... .......... .......... .......... .......... 50%  164M 6s
 18550K .......... .......... .......... .......... .......... 51%  139M 6s
 18600K .......... .......... .......... .......... .......... 51%  157M 6s
 18650K .......... .......... .......... .......... .......... 51%  112M 6s
 18700K .......... .......... .......... .......... .......... 51%  120M 6s
 18750K .......... .......... .......... .......... .......... 51%  101M 6s
 18800K .......... .......... .......... .......... .......... 51%  144M 6s
 18850K .......... .......... .......... .......... .......... 51% 42.6M 6s
 18900K .......... .......... .......... .......... .......... 52% 80.7M 6s
 18950K .......... .......... .......... .......... .......... 52%  133M 6s
 19000K ....

 23750K .......... .......... .......... .......... .......... 65% 49.9M 4s
 23800K .......... .......... .......... .......... .......... 65% 42.3M 4s
 23850K .......... .......... .......... .......... .......... 65% 50.6M 4s
 23900K .......... .......... .......... .......... .......... 65% 37.7M 4s
 23950K .......... .......... .......... .......... .......... 65% 43.9M 4s
 24000K .......... .......... .......... .......... .......... 66% 51.0M 4s
 24050K .......... .......... .......... .......... .......... 66% 31.0M 4s
 24100K .......... .......... .......... .......... .......... 66% 27.3M 4s
 24150K .......... .......... .......... .......... .......... 66% 44.4M 4s
 24200K .......... .......... .......... .......... .......... 66% 40.7M 4s
 24250K .......... .......... .......... .......... .......... 66% 50.4M 4s
 24300K .......... .......... .......... .......... .......... 66%  247K 4s
 24350K .......... .......... .......... .......... .......... 67% 39.5M 4s
 24400K ....

 29150K .......... .......... .......... .......... .......... 80% 41.0M 2s
 29200K .......... .......... .......... .......... .......... 80% 29.7M 2s
 29250K .......... .......... .......... .......... .......... 80% 39.2M 2s
 29300K .......... .......... .......... .......... .......... 80% 26.9M 2s
 29350K .......... .......... .......... .......... .......... 80% 38.8M 2s
 29400K .......... .......... .......... .......... .......... 80% 58.0M 2s
 29450K .......... .......... .......... .......... .......... 81% 49.7M 2s
 29500K .......... .......... .......... .......... .......... 81% 46.1M 2s
 29550K .......... .......... .......... .......... .......... 81% 57.2M 2s
 29600K .......... .......... .......... .......... .......... 81% 69.0M 2s
 29650K .......... .......... .......... .......... .......... 81%  248K 2s
 29700K .......... .......... .......... .......... .......... 81% 48.2M 2s
 29750K .......... .......... .......... .......... .......... 81% 32.9M 2s
 29800K ....

 34550K .......... .......... .......... .......... .......... 95% 68.1M 1s
 34600K .......... .......... .......... .......... .......... 95% 48.7M 1s
 34650K .......... .......... .......... .......... .......... 95% 59.9M 1s
 34700K .......... .......... .......... .......... .......... 95% 62.1M 1s
 34750K .......... .......... .......... .......... .......... 95% 33.1M 1s
 34800K .......... .......... .......... .......... .......... 95% 52.2M 1s
 34850K .......... .......... .......... .......... .......... 95% 38.8M 0s
 34900K .......... .......... .......... .......... .......... 96% 41.0M 0s
 34950K .......... .......... .......... .......... .......... 96% 26.2M 0s
 35000K .......... .......... .......... .......... .......... 96%  245K 0s
 35050K .......... .......... .......... .......... .......... 96% 38.4M 0s
 35100K .......... .......... .......... .......... .......... 96% 43.4M 0s
 35150K .......... .......... .......... .......... .......... 96% 50.6M 0s
 35200K ....

   700K .......... .......... .......... .......... ..........  1% 3.23M 18s
   750K .......... .......... .......... .......... ..........  2%  206M 17s
   800K .......... .......... .......... .......... ..........  2% 4.42M 16s
   850K .......... .......... .......... .......... ..........  2% 12.3M 15s
   900K .......... .......... .......... .......... ..........  2% 15.2M 15s
   950K .......... .......... .......... .......... ..........  2% 3.02M 15s
  1000K .......... .......... .......... .......... ..........  2% 1.19M 15s
  1050K .......... .......... .......... .......... ..........  2% 5.27M 15s
  1100K .......... .......... .......... .......... ..........  3% 3.25M 15s
  1150K .......... .......... .......... .......... ..........  3%  219M 14s
  1200K .......... .......... .......... .......... ..........  3% 8.30M 14s
  1250K .......... .......... .......... .......... ..........  3% 10.7M 13s
  1300K .......... .......... .......... .......... ..........  3% 5.60M 13s

  6050K .......... .......... .......... .......... .......... 16% 96.1M 11s
  6100K .......... .......... .......... .......... .......... 16%  144M 11s
  6150K .......... .......... .......... .......... .......... 16% 91.7M 11s
  6200K .......... .......... .......... .......... .......... 16%  102M 11s
  6250K .......... .......... .......... .......... .......... 16%  130M 11s
  6300K .......... .......... .......... .......... .......... 16%  112M 10s
  6350K .......... .......... .......... .......... .......... 16%  116M 10s
  6400K .......... .......... .......... .......... .......... 17%  129M 10s
  6450K .......... .......... .......... .......... .......... 17% 99.9M 10s
  6500K .......... .......... .......... .......... .......... 17% 76.6M 10s
  6550K .......... .......... .......... .......... .......... 17% 69.9M 10s
  6600K .......... .......... .......... .......... .......... 17% 89.9M 10s
  6650K .......... .......... .......... .......... .......... 17%  246K 11s

 11400K .......... .......... .......... .......... .......... 30% 47.6M 9s
 11450K .......... .......... .......... .......... .......... 30% 54.7M 9s
 11500K .......... .......... .......... .......... .......... 30% 34.8M 9s
 11550K .......... .......... .......... .......... .......... 30% 39.5M 9s
 11600K .......... .......... .......... .......... .......... 30% 42.6M 9s
 11650K .......... .......... .......... .......... .......... 30% 37.4M 9s
 11700K .......... .......... .......... .......... .......... 31% 37.2M 9s
 11750K .......... .......... .......... .......... .......... 31% 38.1M 8s
 11800K .......... .......... .......... .......... .......... 31% 30.2M 8s
 11850K .......... .......... .......... .......... .......... 31% 48.4M 8s
 11900K .......... .......... .......... .......... .......... 31% 33.7M 8s
 11950K .......... .......... .......... .......... .......... 31%  246K 9s
 12000K .......... .......... .......... .......... .......... 31% 50.6M 9s
 12050K ....

 16800K .......... .......... .......... .......... .......... 44%  183M 7s
 16850K .......... .......... .......... .......... .......... 44%  156M 7s
 16900K .......... .......... .......... .......... .......... 44%  146M 7s
 16950K .......... .......... .......... .......... .......... 45%  133M 7s
 17000K .......... .......... .......... .......... .......... 45%  273M 7s
 17050K .......... .......... .......... .......... .......... 45%  124M 7s
 17100K .......... .......... .......... .......... .......... 45%  130M 7s
 17150K .......... .......... .......... .......... .......... 45%  128M 7s
 17200K .......... .......... .......... .......... .......... 45%  129M 7s
 17250K .......... .......... .......... .......... .......... 45%  246K 7s
 17300K .......... .......... .......... .......... .......... 45% 43.3M 7s
 17350K .......... .......... .......... .......... .......... 46% 72.0M 7s
 17400K .......... .......... .......... .......... .......... 46% 63.9M 7s
 17450K ....

 22200K .......... .......... .......... .......... .......... 58% 57.3M 5s
 22250K .......... .......... .......... .......... .......... 59% 52.7M 5s
 22300K .......... .......... .......... .......... .......... 59% 32.2M 5s
 22350K .......... .......... .......... .......... .......... 59% 75.7M 5s
 22400K .......... .......... .......... .......... .......... 59% 40.3M 5s
 22450K .......... .......... .......... .......... .......... 59% 71.9M 5s
 22500K .......... .......... .......... .......... .......... 59%  247K 5s
 22550K .......... .......... .......... .......... .......... 59% 46.3M 5s
 22600K .......... .......... .......... .......... .......... 59% 43.7M 5s
 22650K .......... .......... .......... .......... .......... 60% 60.7M 5s
 22700K .......... .......... .......... .......... .......... 60% 58.1M 5s
 22750K .......... .......... .......... .......... .......... 60% 54.3M 5s
 22800K .......... .......... .......... .......... .......... 60% 76.7M 5s
 22850K ....

 27600K .......... .......... .......... .......... .......... 73% 75.8M 3s
 27650K .......... .......... .......... .......... .......... 73% 88.8M 3s
 27700K .......... .......... .......... .......... .......... 73% 46.6M 3s
 27750K .......... .......... .......... .......... .......... 73% 57.0M 3s
 27800K .......... .......... .......... .......... .......... 73%  245K 3s
 27850K .......... .......... .......... .......... .......... 73% 38.5M 3s
 27900K .......... .......... .......... .......... .......... 74% 36.3M 3s
 27950K .......... .......... .......... .......... .......... 74% 66.1M 3s
 28000K .......... .......... .......... .......... .......... 74% 46.9M 3s
 28050K .......... .......... .......... .......... .......... 74% 45.7M 3s
 28100K .......... .......... .......... .......... .......... 74%  102M 3s
 28150K .......... .......... .......... .......... .......... 74% 52.2M 3s
 28200K .......... .......... .......... .......... .......... 74% 65.3M 3s
 28250K ....

 33000K .......... .......... .......... .......... .......... 87% 50.2M 2s
 33050K .......... .......... .......... .......... .......... 87% 57.7M 2s
 33100K .......... .......... .......... .......... .......... 87%  245K 2s
 33150K .......... .......... .......... .......... .......... 87% 60.1M 2s
 33200K .......... .......... .......... .......... .......... 88%  140M 1s
 33250K .......... .......... .......... .......... .......... 88%  146M 1s
 33300K .......... .......... .......... .......... .......... 88%  135M 1s
 33350K .......... .......... .......... .......... .......... 88%  161M 1s
 33400K .......... .......... .......... .......... .......... 88%  223M 1s
 33450K .......... .......... .......... .......... .......... 88%  151M 1s
 33500K .......... .......... .......... .......... .......... 88%  163M 1s
 33550K .......... .......... .......... .......... .......... 88%  205M 1s
 33600K .......... .......... .......... .......... .......... 89%  160M 1s
 33650K ....

   300K .......... .......... .......... .......... .......... 15%  114M 1s
   350K .......... .......... .......... .......... .......... 17% 1.11M 1s
   400K .......... .......... .......... .......... .......... 20% 15.4M 1s
   450K .......... .......... .......... .......... .......... 22% 3.32M 1s
   500K .......... .......... .......... .......... .......... 24% 70.3M 1s
   550K .......... .......... .......... .......... .......... 26%  820K 1s
   600K .......... .......... .......... .......... .......... 29% 6.06M 1s
   650K .......... .......... .......... .......... .......... 31% 11.5M 1s
   700K .......... .......... .......... .......... .......... 33% 2.83M 1s
   750K .......... .......... .......... .......... .......... 35% 16.6M 1s
   800K .......... .......... .......... .......... .......... 38% 10.6M 1s
   850K .......... .......... .......... .......... .......... 40% 3.11M 1s
   900K .......... .......... .......... .......... .......... 42% 11.1M 1s
   950K ....

  3100K .......... .......... .......... .......... ..........  8% 35.9M 12s
  3150K .......... .......... .......... .......... ..........  8% 12.7M 12s
  3200K .......... .......... .......... .......... ..........  8% 30.3M 12s
  3250K .......... .......... .......... .......... ..........  8% 52.0M 12s
  3300K .......... .......... .......... .......... ..........  8% 50.1M 12s
  3350K .......... .......... .......... .......... ..........  8% 71.7M 11s
  3400K .......... .......... .......... .......... ..........  8%  248K 13s
  3450K .......... .......... .......... .......... ..........  9% 44.8M 13s
  3500K .......... .......... .......... .......... ..........  9% 58.1M 13s
  3550K .......... .......... .......... .......... ..........  9% 61.9M 13s
  3600K .......... .......... .......... .......... ..........  9% 49.1M 12s
  3650K .......... .......... .......... .......... ..........  9% 46.4M 12s
  3700K .......... .......... .......... .......... ..........  9% 48.4M 12s

  8450K .......... .......... .......... .......... .......... 22% 83.2M 10s
  8500K .......... .......... .......... .......... .......... 22% 41.0M 10s
  8550K .......... .......... .......... .......... .......... 22% 18.2M 10s
  8600K .......... .......... .......... .......... .......... 22% 13.9M 10s
  8650K .......... .......... .......... .......... .......... 22%  121M 10s
  8700K .......... .......... .......... .......... .......... 22%  247K 10s
  8750K .......... .......... .......... .......... .......... 22% 42.0M 10s
  8800K .......... .......... .......... .......... .......... 22% 67.7M 10s
  8850K .......... .......... .......... .......... .......... 23% 69.1M 10s
  8900K .......... .......... .......... .......... .......... 23% 42.1M 10s
  8950K .......... .......... .......... .......... .......... 23% 53.0M 10s
  9000K .......... .......... .......... .......... .......... 23% 56.5M 10s
  9050K .......... .......... .......... .......... .......... 23% 51.3M 10s

 13850K .......... .......... .......... .......... .......... 36% 46.2M 8s
 13900K .......... .......... .......... .......... .......... 36% 59.4M 8s
 13950K .......... .......... .......... .......... .......... 36%  247K 8s
 14000K .......... .......... .......... .......... .......... 36% 59.8M 8s
 14050K .......... .......... .......... .......... .......... 36% 67.1M 8s
 14100K .......... .......... .......... .......... .......... 36% 96.3M 8s
 14150K .......... .......... .......... .......... .......... 36% 68.3M 8s
 14200K .......... .......... .......... .......... .......... 37% 66.5M 8s
 14250K .......... .......... .......... .......... .......... 37% 58.6M 8s
 14300K .......... .......... .......... .......... .......... 37% 87.4M 8s
 14350K .......... .......... .......... .......... .......... 37% 47.0M 8s
 14400K .......... .......... .......... .......... .......... 37% 72.5M 8s
 14450K .......... .......... .......... .......... .......... 37% 24.4M 8s
 14500K ....

 19250K .......... .......... .......... .......... .......... 50% 43.1M 6s
 19300K .......... .......... .......... .......... .......... 50%  246K 6s
 19350K .......... .......... .......... .......... .......... 50% 45.7M 6s
 19400K .......... .......... .......... .......... .......... 50% 59.0M 6s
 19450K .......... .......... .......... .......... .......... 50% 57.3M 6s
 19500K .......... .......... .......... .......... .......... 50% 45.1M 6s
 19550K .......... .......... .......... .......... .......... 50% 34.4M 6s
 19600K .......... .......... .......... .......... .......... 51% 44.0M 6s
 19650K .......... .......... .......... .......... .......... 51% 34.1M 6s
 19700K .......... .......... .......... .......... .......... 51% 41.9M 6s
 19750K .......... .......... .......... .......... .......... 51% 44.4M 6s
 19800K .......... .......... .......... .......... .......... 51% 46.3M 6s
 19850K .......... .......... .......... .......... .......... 51% 55.6M 6s
 19900K ....

 24650K .......... .......... .......... .......... .......... 64% 44.5M 5s
 24700K .......... .......... .......... .......... .......... 64% 44.9M 5s
 24750K .......... .......... .......... .......... .......... 64% 51.7M 5s
 24800K .......... .......... .......... .......... .......... 64% 40.1M 4s
 24850K .......... .......... .......... .......... .......... 64% 52.4M 4s
 24900K .......... .......... .......... .......... .......... 64% 61.8M 4s
 24950K .......... .......... .......... .......... .......... 64% 79.3M 4s
 25000K .......... .......... .......... .......... .......... 65% 55.7M 4s
 25050K .......... .......... .......... .......... .......... 65% 66.7M 4s
 25100K .......... .......... .......... .......... .......... 65% 37.9M 4s
 25150K .......... .......... .......... .......... .......... 65% 34.0M 4s
 25200K .......... .......... .......... .......... .......... 65%  244K 4s
 25250K .......... .......... .......... .......... .......... 65% 28.7M 4s
 25300K ....

 30050K .......... .......... .......... .......... .......... 78% 59.8M 3s
 30100K .......... .......... .......... .......... .......... 78% 42.2M 3s
 30150K .......... .......... .......... .......... .......... 78% 49.7M 3s
 30200K .......... .......... .......... .......... .......... 78% 42.5M 3s
 30250K .......... .......... .......... .......... .......... 78% 48.3M 3s
 30300K .......... .......... .......... .......... .......... 78% 38.5M 3s
 30350K .......... .......... .......... .......... .......... 78% 72.6M 3s
 30400K .......... .......... .......... .......... .......... 79% 42.1M 3s
 30450K .......... .......... .......... .......... .......... 79% 53.1M 3s
 30500K .......... .......... .......... .......... .......... 79% 39.8M 3s
 30550K .......... .......... .......... .......... .......... 79%  246K 3s
 30600K .......... .......... .......... .......... .......... 79%  286M 3s
 30650K .......... .......... .......... .......... .......... 79%  159M 3s
 30700K ....

 35450K .......... .......... .......... .......... .......... 92% 40.8M 1s
 35500K .......... .......... .......... .......... .......... 92% 69.3M 1s
 35550K .......... .......... .......... .......... .......... 92% 49.8M 1s
 35600K .......... .......... .......... .......... .......... 92% 47.3M 1s
 35650K .......... .......... .......... .......... .......... 92% 41.4M 1s
 35700K .......... .......... .......... .......... .......... 92% 40.6M 1s
 35750K .......... .......... .......... .......... .......... 92% 39.4M 1s
 35800K .......... .......... .......... .......... .......... 93% 30.4M 1s
 35850K .......... .......... .......... .......... .......... 93%  246K 1s
 35900K .......... .......... .......... .......... .......... 93% 34.5M 1s
 35950K .......... .......... .......... .......... .......... 93% 45.7M 1s
 36000K .......... .......... .......... .......... .......... 93% 60.7M 1s
 36050K .......... .......... .......... .......... .......... 93% 40.5M 1s
 36100K ....

  2000K .......... .......... .......... .......... .......... 86% 16.2M 0s
  2050K .......... .......... .......... .......... .......... 89% 3.58M 0s
  2100K .......... .......... .......... .......... .......... 91%  144M 0s
  2150K .......... .......... .......... .......... .......... 93% 1.05M 0s
  2200K .......... .......... .......... .......... .......... 95% 14.3M 0s
  2250K .......... .......... .......... .......... .......... 97% 4.76M 0s
  2300K .......... .......... .......... .......... .......... 99% 5.47M 0s
  2350K ........                                              100% 74.3M=0.9s

2022-06-10 13:53:00 (2.54 MB/s) - ‘11209_2021_dayl.nc’ saved [2414819/2414819]



In [5]:
%%sh
ls -lt 11207_*_*.nc 11208_*_*.nc 11209_*_*.nc

-rw-r--r-- 1 jrw jrw  2414819 Jun 10 13:53 11209_2021_dayl.nc
-rw-r--r-- 1 jrw jrw 39425832 Jun 10 13:52 11209_2021_vp.nc
-rw-r--r-- 1 jrw jrw  2280920 Jun 10 13:52 11208_2021_dayl.nc
-rw-r--r-- 1 jrw jrw 38665614 Jun 10 13:52 11208_2021_vp.nc
-rw-r--r-- 1 jrw jrw  2157873 Jun 10 13:52 11207_2021_dayl.nc
-rw-r--r-- 1 jrw jrw 37274017 Jun 10 13:51 11207_2021_vp.nc
-rw-r--r-- 1 jrw jrw 77764456 Jun 10 13:51 11209_2020_dayl.nc
-rw-r--r-- 1 jrw jrw 77764484 Jun 10 13:50 11209_2020_vp.nc
-rw-r--r-- 1 jrw jrw 75383612 Jun 10 13:50 11208_2020_dayl.nc
-rw-r--r-- 1 jrw jrw 75383640 Jun 10 13:49 11208_2020_vp.nc
-rw-r--r-- 1 jrw jrw 72732652 Jun 10 13:49 11207_2020_dayl.nc
-rw-r--r-- 1 jrw jrw 72732680 Jun 10 13:48 11207_2020_vp.nc


Download dayl nc files for tiles 13166 11933, and 9402 over years between 2019 and 2021

In [6]:
%%sh
bash ../Bash/daymet_tile-nc-retrieval.sh -s 2019 -e 2021 -v "dayl" -t "13166 11933 9402" 

--2022-06-10 13:55:04--  https://thredds.daac.ornl.gov/thredds/fileServer/ornldaac/1840/tiles/2019/13166_2019/dayl.nc
Resolving thredds.daac.ornl.gov (thredds.daac.ornl.gov)... 160.91.19.90
Connecting to thredds.daac.ornl.gov (thredds.daac.ornl.gov)|160.91.19.90|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67551788 (64M) [application/x-netcdf]
Saving to: ‘13166_2019_dayl.nc’

     0K .......... .......... .......... .......... ..........  0%  368K 2m59s
    50K .......... .......... .......... .......... ..........  0%  918K 2m5s
   100K .......... .......... .......... .......... ..........  0% 9.89M 86s
   150K .......... .......... .......... .......... ..........  0% 13.6M 65s
   200K .......... .......... .......... .......... ..........  0% 1.03M 65s
   250K .......... .......... .......... .......... ..........  0% 3.52M 57s
   300K .......... .......... .......... .......... ..........  0% 99.6M 49s
   350K .......... .......... .......... .........

  5100K .......... .......... .......... .......... ..........  7% 48.5M 20s
  5150K .......... .......... .......... .......... ..........  7% 59.9M 20s
  5200K .......... .......... .......... .......... ..........  7%  248K 22s
  5250K .......... .......... .......... .......... ..........  8% 22.0M 22s
  5300K .......... .......... .......... .......... ..........  8% 95.9M 21s
  5350K .......... .......... .......... .......... ..........  8% 81.5M 21s
  5400K .......... .......... .......... .......... ..........  8% 82.2M 21s
  5450K .......... .......... .......... .......... ..........  8% 90.8M 21s
  5500K .......... .......... .......... .......... ..........  8% 42.8M 21s
  5550K .......... .......... .......... .......... ..........  8% 52.9M 20s
  5600K .......... .......... .......... .......... ..........  8% 84.3M 20s
  5650K .......... .......... .......... .......... ..........  8% 77.1M 20s
  5700K .......... .......... .......... .......... ..........  8% 64.8M 20s

 10450K .......... .......... .......... .......... .......... 15% 31.4M 18s
 10500K .......... .......... .......... .......... .......... 15%  248K 19s
 10550K .......... .......... .......... .......... .......... 16% 57.0M 19s
 10600K .......... .......... .......... .......... .......... 16% 79.7M 19s
 10650K .......... .......... .......... .......... .......... 16%  112M 19s
 10700K .......... .......... .......... .......... .......... 16%  102M 18s
 10750K .......... .......... .......... .......... .......... 16%  113M 18s
 10800K .......... .......... .......... .......... .......... 16% 47.6M 18s
 10850K .......... .......... .......... .......... .......... 16% 40.8M 18s
 10900K .......... .......... .......... .......... .......... 16% 47.2M 18s
 10950K .......... .......... .......... .......... .......... 16% 40.1M 18s
 11000K .......... .......... .......... .......... .......... 16% 36.7M 18s
 11050K .......... .......... .......... .......... .......... 16% 48.8M 18s

 15800K .......... .......... .......... .......... .......... 24%  245K 17s
 15850K .......... .......... .......... .......... .......... 24% 35.2M 17s
 15900K .......... .......... .......... .......... .......... 24% 45.3M 17s
 15950K .......... .......... .......... .......... .......... 24% 36.5M 17s
 16000K .......... .......... .......... .......... .......... 24% 26.7M 17s
 16050K .......... .......... .......... .......... .......... 24% 44.3M 17s
 16100K .......... .......... .......... .......... .......... 24% 35.8M 16s
 16150K .......... .......... .......... .......... .......... 24% 40.5M 16s
 16200K .......... .......... .......... .......... .......... 24% 47.7M 16s
 16250K .......... .......... .......... .......... .......... 24% 76.5M 16s
 16300K .......... .......... .......... .......... .......... 24% 42.2M 16s
 16350K .......... .......... .......... .......... .......... 24% 36.2M 16s
 16400K .......... .......... .......... .......... .......... 24% 50.2M 16s

 21150K .......... .......... .......... .......... .......... 32% 47.8M 15s
 21200K .......... .......... .......... .......... .......... 32% 73.6M 15s
 21250K .......... .......... .......... .......... .......... 32%  246K 15s
 21300K .......... .......... .......... .......... .......... 32% 36.9M 15s
 21350K .......... .......... .......... .......... .......... 32% 55.6M 15s
 21400K .......... .......... .......... .......... .......... 32% 39.1M 15s
 21450K .......... .......... .......... .......... .......... 32% 48.2M 15s
 21500K .......... .......... .......... .......... .......... 32% 41.5M 15s
 21550K .......... .......... .......... .......... .......... 32% 44.4M 15s
 21600K .......... .......... .......... .......... .......... 32% 37.0M 15s
 21650K .......... .......... .......... .......... .......... 32% 46.2M 14s
 21700K .......... .......... .......... .......... .......... 32% 35.3M 14s
 21750K .......... .......... .......... .......... .......... 33% 44.1M 14s

 26500K .......... .......... .......... .......... .......... 40% 58.3M 13s
 26550K .......... .......... .......... .......... .......... 40% 31.5M 13s
 26600K .......... .......... .......... .......... .......... 40%  247K 13s
 26650K .......... .......... .......... .......... .......... 40% 36.2M 13s
 26700K .......... .......... .......... .......... .......... 40% 49.4M 13s
 26750K .......... .......... .......... .......... .......... 40% 55.5M 13s
 26800K .......... .......... .......... .......... .......... 40% 74.3M 13s
 26850K .......... .......... .......... .......... .......... 40% 19.3M 13s
 26900K .......... .......... .......... .......... .......... 40% 44.8M 13s
 26950K .......... .......... .......... .......... .......... 40% 62.8M 13s
 27000K .......... .......... .......... .......... .......... 41% 53.4M 13s
 27050K .......... .......... .......... .......... .......... 41% 26.1M 13s
 27100K .......... .......... .......... .......... .......... 41% 54.0M 13s

 31850K .......... .......... .......... .......... .......... 48% 30.2M 11s
 31900K .......... .......... .......... .......... .......... 48%  247K 11s
 31950K .......... .......... .......... .......... .......... 48% 59.2M 11s
 32000K .......... .......... .......... .......... .......... 48% 59.9M 11s
 32050K .......... .......... .......... .......... .......... 48% 47.3M 11s
 32100K .......... .......... .......... .......... .......... 48% 59.2M 11s
 32150K .......... .......... .......... .......... .......... 48% 62.8M 11s
 32200K .......... .......... .......... .......... .......... 48% 49.6M 11s
 32250K .......... .......... .......... .......... .......... 48% 49.7M 11s
 32300K .......... .......... .......... .......... .......... 49% 54.2M 11s
 32350K .......... .......... .......... .......... .......... 49% 35.7M 11s
 32400K .......... .......... .......... .......... .......... 49% 30.7M 11s
 32450K .......... .......... .......... .......... .......... 49% 24.8M 11s

 37200K .......... .......... .......... .......... .......... 56% 64.9M 9s
 37250K .......... .......... .......... .......... .......... 56%  248K 9s
 37300K .......... .......... .......... .......... .......... 56%  118M 9s
 37350K .......... .......... .......... .......... .......... 56%  118M 9s
 37400K .......... .......... .......... .......... .......... 56%  122M 9s
 37450K .......... .......... .......... .......... .......... 56%  149M 9s
 37500K .......... .......... .......... .......... .......... 56% 79.1M 9s
 37550K .......... .......... .......... .......... .......... 56% 85.8M 9s
 37600K .......... .......... .......... .......... .......... 57%  143M 9s
 37650K .......... .......... .......... .......... .......... 57% 78.7M 9s
 37700K .......... .......... .......... .......... .......... 57% 96.4M 9s
 37750K .......... .......... .......... .......... .......... 57%  122M 9s
 37800K .......... .......... .......... .......... .......... 57% 87.2M 9s
 37850K ....

 42600K .......... .......... .......... .......... .......... 64% 43.7M 8s
 42650K .......... .......... .......... .......... .......... 64%  247K 8s
 42700K .......... .......... .......... .......... .......... 64% 51.0M 8s
 42750K .......... .......... .......... .......... .......... 64% 47.7M 8s
 42800K .......... .......... .......... .......... .......... 64% 43.6M 8s
 42850K .......... .......... .......... .......... .......... 65% 54.5M 8s
 42900K .......... .......... .......... .......... .......... 65% 55.0M 8s
 42950K .......... .......... .......... .......... .......... 65% 57.9M 8s
 43000K .......... .......... .......... .......... .......... 65% 39.7M 7s
 43050K .......... .......... .......... .......... .......... 65% 34.5M 7s
 43100K .......... .......... .......... .......... .......... 65% 40.2M 7s
 43150K .......... .......... .......... .......... .......... 65% 60.8M 7s
 43200K .......... .......... .......... .......... .......... 65% 41.4M 7s
 43250K ....

 48000K .......... .......... .......... .......... .......... 72% 77.6M 6s
 48050K .......... .......... .......... .......... .......... 72% 89.3M 6s
 48100K .......... .......... .......... .......... .......... 72%  117M 6s
 48150K .......... .......... .......... .......... .......... 73% 97.3M 6s
 48200K .......... .......... .......... .......... .......... 73%  136M 6s
 48250K .......... .......... .......... .......... .......... 73%  146M 6s
 48300K .......... .......... .......... .......... .......... 73%  125M 6s
 48350K .......... .......... .......... .......... .......... 73%  133M 6s
 48400K .......... .......... .......... .......... .......... 73% 90.5M 6s
 48450K .......... .......... .......... .......... .......... 73% 94.4M 6s
 48500K .......... .......... .......... .......... .......... 73% 83.3M 6s
 48550K .......... .......... .......... .......... .......... 73%  246K 6s
 48600K .......... .......... .......... .......... .......... 73% 47.2M 6s
 48650K ....

 53400K .......... .......... .......... .......... .......... 81% 47.5M 4s
 53450K .......... .......... .......... .......... .......... 81% 36.1M 4s
 53500K .......... .......... .......... .......... .......... 81% 48.6M 4s
 53550K .......... .......... .......... .......... .......... 81% 33.0M 4s
 53600K .......... .......... .......... .......... .......... 81% 30.0M 4s
 53650K .......... .......... .......... .......... .......... 81% 34.4M 4s
 53700K .......... .......... .......... .......... .......... 81% 31.7M 4s
 53750K .......... .......... .......... .......... .......... 81% 20.4M 4s
 53800K .......... .......... .......... .......... .......... 81% 27.4M 4s
 53850K .......... .......... .......... .......... .......... 81% 31.6M 4s
 53900K .......... .......... .......... .......... .......... 81% 42.1M 4s
 53950K .......... .......... .......... .......... .......... 81%  247K 4s
 54000K .......... .......... .......... .......... .......... 81% 54.4M 4s
 54050K ....

 58800K .......... .......... .......... .......... .......... 89% 44.0M 2s
 58850K .......... .......... .......... .......... .......... 89% 89.9M 2s
 58900K .......... .......... .......... .......... .......... 89% 17.3M 2s
 58950K .......... .......... .......... .......... .......... 89% 33.3M 2s
 59000K .......... .......... .......... .......... .......... 89% 25.7M 2s
 59050K .......... .......... .......... .......... .......... 89% 38.5M 2s
 59100K .......... .......... .......... .......... .......... 89% 37.7M 2s
 59150K .......... .......... .......... .......... .......... 89% 35.5M 2s
 59200K .......... .......... .......... .......... .......... 89% 52.0M 2s
 59250K .......... .......... .......... .......... .......... 89%  247K 2s
 59300K .......... .......... .......... .......... .......... 89% 49.6M 2s
 59350K .......... .......... .......... .......... .......... 90% 39.7M 2s
 59400K .......... .......... .......... .......... .......... 90% 36.3M 2s
 59450K ....

 64200K .......... .......... .......... .......... .......... 97% 40.4M 1s
 64250K .......... .......... .......... .......... .......... 97% 70.2M 1s
 64300K .......... .......... .......... .......... .......... 97% 48.5M 1s
 64350K .......... .......... .......... .......... .......... 97% 32.1M 1s
 64400K .......... .......... .......... .......... .......... 97% 21.1M 0s
 64450K .......... .......... .......... .......... .......... 97% 52.9M 0s
 64500K .......... .......... .......... .......... .......... 97% 45.9M 0s
 64550K .......... .......... .......... .......... .......... 97%  246K 0s
 64600K .......... .......... .......... .......... .......... 98% 35.4M 0s
 64650K .......... .......... .......... .......... .......... 98% 38.3M 0s
 64700K .......... .......... .......... .......... .......... 98% 35.7M 0s
 64750K .......... .......... .......... .......... .......... 98% 34.9M 0s
 64800K .......... .......... .......... .......... .......... 98% 41.6M 0s
 64850K ....

  3250K .......... .......... .......... .......... ..........  4% 14.3M 24s
  3300K .......... .......... .......... .......... ..........  4% 2.11M 24s
  3350K .......... .......... .......... .......... ..........  4% 14.6M 24s
  3400K .......... .......... .......... .......... ..........  4% 7.73M 23s
  3450K .......... .......... .......... .......... ..........  4% 4.02M 23s
  3500K .......... .......... .......... .......... ..........  4% 5.41M 23s
  3550K .......... .......... .......... .......... ..........  4% 7.41M 23s
  3600K .......... .......... .......... .......... ..........  4% 1.99M 23s
  3650K .......... .......... .......... .......... ..........  4% 9.84M 23s
  3700K .......... .......... .......... .......... ..........  4%  246K 26s
  3750K .......... .......... .......... .......... ..........  5% 43.6M 26s
  3800K .......... .......... .......... .......... ..........  5% 51.8M 26s
  3850K .......... .......... .......... .......... ..........  5% 50.6M 25s

  8600K .......... .......... .......... .......... .......... 11% 36.6M 23s
  8650K .......... .......... .......... .......... .......... 11% 42.4M 22s
  8700K .......... .......... .......... .......... .......... 11% 52.1M 22s
  8750K .......... .......... .......... .......... .......... 11% 37.1M 22s
  8800K .......... .......... .......... .......... .......... 11% 34.2M 22s
  8850K .......... .......... .......... .......... .......... 11% 37.7M 22s
  8900K .......... .......... .......... .......... .......... 11% 47.7M 22s
  8950K .......... .......... .......... .......... .......... 11% 54.3M 22s
  9000K .......... .......... .......... .......... .......... 11% 36.8M 21s
  9050K .......... .......... .......... .......... .......... 12%  248K 23s
  9100K .......... .......... .......... .......... .......... 12% 42.0M 23s
  9150K .......... .......... .......... .......... .......... 12% 47.5M 23s
  9200K .......... .......... .......... .......... .......... 12% 48.9M 22s

 13950K .......... .......... .......... .......... .......... 18% 52.9M 20s
 14000K .......... .......... .......... .......... .......... 18% 60.9M 20s
 14050K .......... .......... .......... .......... .......... 18% 51.8M 20s
 14100K .......... .......... .......... .......... .......... 18% 60.7M 20s
 14150K .......... .......... .......... .......... .......... 18% 67.0M 20s
 14200K .......... .......... .......... .......... .......... 18% 19.5M 20s
 14250K .......... .......... .......... .......... .......... 18% 23.5M 20s
 14300K .......... .......... .......... .......... .......... 19% 48.2M 20s
 14350K .......... .......... .......... .......... .......... 19% 49.4M 20s
 14400K .......... .......... .......... .......... .......... 19%  247K 21s
 14450K .......... .......... .......... .......... .......... 19% 95.7M 20s
 14500K .......... .......... .......... .......... .......... 19% 62.0M 20s
 14550K .......... .......... .......... .......... .......... 19% 55.6M 20s

 19300K .......... .......... .......... .......... .......... 25% 40.7M 18s
 19350K .......... .......... .......... .......... .......... 25% 28.0M 18s
 19400K .......... .......... .......... .......... .......... 25% 30.4M 18s
 19450K .......... .......... .......... .......... .......... 25% 32.0M 18s
 19500K .......... .......... .......... .......... .......... 25% 49.6M 18s
 19550K .......... .......... .......... .......... .......... 25% 63.7M 18s
 19600K .......... .......... .......... .......... .......... 26% 27.1M 18s
 19650K .......... .......... .......... .......... .......... 26%  249K 19s
 19700K .......... .......... .......... .......... .......... 26%  211M 19s
 19750K .......... .......... .......... .......... .......... 26%  268M 18s
 19800K .......... .......... .......... .......... .......... 26%  239M 18s
 19850K .......... .......... .......... .......... .......... 26%  274M 18s
 19900K .......... .......... .......... .......... .......... 26%  335M 18s

 24650K .......... .......... .......... .......... .......... 32% 76.6M 17s
 24700K .......... .......... .......... .......... .......... 32% 26.3M 17s
 24750K .......... .......... .......... .......... .......... 32% 59.2M 16s
 24800K .......... .......... .......... .......... .......... 32% 47.3M 16s
 24850K .......... .......... .......... .......... .......... 33% 33.2M 16s
 24900K .......... .......... .......... .......... .......... 33%  245K 17s
 24950K .......... .......... .......... .......... .......... 33% 36.6M 17s
 25000K .......... .......... .......... .......... .......... 33% 42.4M 17s
 25050K .......... .......... .......... .......... .......... 33% 49.1M 17s
 25100K .......... .......... .......... .......... .......... 33% 41.2M 17s
 25150K .......... .......... .......... .......... .......... 33% 49.2M 17s
 25200K .......... .......... .......... .......... .......... 33% 48.7M 16s
 25250K .......... .......... .......... .......... .......... 33% 47.4M 16s

 30000K .......... .......... .......... .......... .......... 39% 26.3M 15s
 30050K .......... .......... .......... .......... .......... 39% 50.8M 15s
 30100K .......... .......... .......... .......... .......... 39% 41.3M 15s
 30150K .......... .......... .......... .......... .......... 40% 73.9M 15s
 30200K .......... .......... .......... .......... .......... 40%  246K 15s
 30250K .......... .......... .......... .......... .......... 40% 24.8M 15s
 30300K .......... .......... .......... .......... .......... 40% 43.9M 15s
 30350K .......... .......... .......... .......... .......... 40% 43.9M 15s
 30400K .......... .......... .......... .......... .......... 40% 36.1M 15s
 30450K .......... .......... .......... .......... .......... 40% 27.0M 15s
 30500K .......... .......... .......... .......... .......... 40% 36.5M 15s
 30550K .......... .......... .......... .......... .......... 40% 33.8M 15s
 30600K .......... .......... .......... .......... .......... 40% 26.4M 15s

 35350K .......... .......... .......... .......... .......... 46% 74.1M 13s
 35400K .......... .......... .......... .......... .......... 46% 56.1M 13s
 35450K .......... .......... .......... .......... .......... 47% 43.1M 13s
 35500K .......... .......... .......... .......... .......... 47% 42.6M 13s
 35550K .......... .......... .......... .......... .......... 47% 27.0M 13s
 35600K .......... .......... .......... .......... .......... 47% 22.6M 13s
 35650K .......... .......... .......... .......... .......... 47%  247K 13s
 35700K .......... .......... .......... .......... .......... 47% 34.1M 13s
 35750K .......... .......... .......... .......... .......... 47% 34.4M 13s
 35800K .......... .......... .......... .......... .......... 47% 58.1M 13s
 35850K .......... .......... .......... .......... .......... 47% 45.5M 13s
 35900K .......... .......... .......... .......... .......... 47% 46.2M 13s
 35950K .......... .......... .......... .......... .......... 47% 60.3M 13s

 40700K .......... .......... .......... .......... .......... 54%  129M 11s
 40750K .......... .......... .......... .......... .......... 54%  116M 11s
 40800K .......... .......... .......... .......... .......... 54%  152M 11s
 40850K .......... .......... .......... .......... .......... 54%  113M 11s
 40900K .......... .......... .......... .......... .......... 54%  248K 11s
 40950K .......... .......... .......... .......... .......... 54% 39.9M 11s
 41000K .......... .......... .......... .......... .......... 54% 80.3M 11s
 41050K .......... .......... .......... .......... .......... 54% 41.4M 11s
 41100K .......... .......... .......... .......... .......... 54% 40.7M 11s
 41150K .......... .......... .......... .......... .......... 54% 65.5M 11s
 41200K .......... .......... .......... .......... .......... 54% 54.3M 11s
 41250K .......... .......... .......... .......... .......... 54% 30.0M 11s
 41300K .......... .......... .......... .......... .......... 54% 42.9M 11s

 46050K .......... .......... .......... .......... .......... 61% 90.0M 10s
 46100K .......... .......... .......... .......... .......... 61%  127M 10s
 46150K .......... .......... .......... .......... .......... 61% 77.1M 10s
 46200K .......... .......... .......... .......... .......... 61% 89.7M 9s
 46250K .......... .......... .......... .......... .......... 61%  246K 10s
 46300K .......... .......... .......... .......... .......... 61% 46.4M 10s
 46350K .......... .......... .......... .......... .......... 61% 43.5M 10s
 46400K .......... .......... .......... .......... .......... 61% 42.2M 10s
 46450K .......... .......... .......... .......... .......... 61% 56.6M 9s
 46500K .......... .......... .......... .......... .......... 61% 31.0M 9s
 46550K .......... .......... .......... .......... .......... 61% 48.6M 9s
 46600K .......... .......... .......... .......... .......... 61% 38.3M 9s
 46650K .......... .......... .......... .......... .......... 61% 51.7M 9s
 4670

 51450K .......... .......... .......... .......... .......... 68% 12.4M 8s
 51500K .......... .......... .......... .......... .......... 68% 15.5M 8s
 51550K .......... .......... .......... .......... .......... 68% 34.5M 8s
 51600K .......... .......... .......... .......... .......... 68% 36.0M 8s
 51650K .......... .......... .......... .......... .......... 68%  244K 8s
 51700K .......... .......... .......... .......... .......... 68% 38.2M 8s
 51750K .......... .......... .......... .......... .......... 68% 51.3M 8s
 51800K .......... .......... .......... .......... .......... 68% 37.2M 8s
 51850K .......... .......... .......... .......... .......... 68% 32.3M 8s
 51900K .......... .......... .......... .......... .......... 68% 37.4M 8s
 51950K .......... .......... .......... .......... .......... 68% 35.3M 8s
 52000K .......... .......... .......... .......... .......... 68% 45.2M 8s
 52050K .......... .......... .......... .......... .......... 69% 55.4M 8s
 52100K ....

 56850K .......... .......... .......... .......... .......... 75% 25.7M 6s
 56900K .......... .......... .......... .......... .......... 75% 37.2M 6s
 56950K .......... .......... .......... .......... .......... 75% 32.8M 6s
 57000K .......... .......... .......... .......... .......... 75% 28.7M 6s
 57050K .......... .......... .......... .......... .......... 75%  247K 6s
 57100K .......... .......... .......... .......... .......... 75% 73.3M 6s
 57150K .......... .......... .......... .......... .......... 75% 92.7M 6s
 57200K .......... .......... .......... .......... .......... 75%  129M 6s
 57250K .......... .......... .......... .......... .......... 75% 94.5M 6s
 57300K .......... .......... .......... .......... .......... 76%  111M 6s
 57350K .......... .......... .......... .......... .......... 76% 36.3M 6s
 57400K .......... .......... .......... .......... .......... 76% 46.4M 6s
 57450K .......... .......... .......... .......... .......... 76% 49.2M 6s
 57500K ....

 62250K .......... .......... .......... .......... .......... 82% 37.4M 4s
 62300K .......... .......... .......... .......... .......... 82% 29.9M 4s
 62350K .......... .......... .......... .......... .......... 82% 25.4M 4s
 62400K .......... .......... .......... .......... .......... 82%  246K 4s
 62450K .......... .......... .......... .......... .......... 82% 73.5M 4s
 62500K .......... .......... .......... .......... .......... 82% 46.0M 4s
 62550K .......... .......... .......... .......... .......... 82% 44.6M 4s
 62600K .......... .......... .......... .......... .......... 83% 48.9M 4s
 62650K .......... .......... .......... .......... .......... 83% 46.5M 4s
 62700K .......... .......... .......... .......... .......... 83% 42.3M 4s
 62750K .......... .......... .......... .......... .......... 83% 46.8M 4s
 62800K .......... .......... .......... .......... .......... 83% 37.5M 4s
 62850K .......... .......... .......... .......... .......... 83% 38.1M 4s
 62900K ....

 67650K .......... .......... .......... .......... .......... 89% 57.5M 3s
 67700K .......... .......... .......... .......... .......... 89%  248K 3s
 67750K .......... .......... .......... .......... .......... 89% 62.0M 3s
 67800K .......... .......... .......... .......... .......... 89% 59.2M 2s
 67850K .......... .......... .......... .......... .......... 90% 48.2M 2s
 67900K .......... .......... .......... .......... .......... 90% 71.4M 2s
 67950K .......... .......... .......... .......... .......... 90% 48.5M 2s
 68000K .......... .......... .......... .......... .......... 90% 42.5M 2s
 68050K .......... .......... .......... .......... .......... 90% 46.2M 2s
 68100K .......... .......... .......... .......... .......... 90% 70.4M 2s
 68150K .......... .......... .......... .......... .......... 90% 81.3M 2s
 68200K .......... .......... .......... .......... .......... 90% 38.1M 2s
 68250K .......... .......... .......... .......... .......... 90% 34.0M 2s
 68300K ....

 73050K .......... .......... .......... .......... .......... 96% 44.6M 1s
 73100K .......... .......... .......... .......... .......... 96% 59.8M 1s
 73150K .......... .......... .......... .......... .......... 97% 44.6M 1s
 73200K .......... .......... .......... .......... .......... 97% 49.1M 1s
 73250K .......... .......... .......... .......... .......... 97% 66.4M 1s
 73300K .......... .......... .......... .......... .......... 97% 47.8M 1s
 73350K .......... .......... .......... .......... .......... 97% 51.4M 1s
 73400K .......... .......... .......... .......... .......... 97% 53.4M 1s
 73450K .......... .......... .......... .......... .......... 97% 36.8M 1s
 73500K .......... .......... .......... .......... .......... 97% 32.4M 1s
 73550K .......... .......... .......... .......... .......... 97% 36.3M 1s
 73600K .......... .......... .......... .......... .......... 97% 28.6M 1s
 73650K .......... .......... .......... .......... .......... 97% 26.1M 1s
 73700K ....

  2700K .......... .......... .......... .......... .......... 21% 52.7M 4s
  2750K .......... .......... .......... .......... .......... 21% 50.9M 4s
  2800K .......... .......... .......... .......... .......... 21% 34.9M 4s
  2850K .......... .......... .......... .......... .......... 22% 39.1M 4s
  2900K .......... .......... .......... .......... .......... 22% 44.9M 3s
  2950K .......... .......... .......... .......... .......... 22% 31.7M 3s
  3000K .......... .......... .......... .......... .......... 23% 44.7M 3s
  3050K .......... .......... .......... .......... .......... 23% 57.5M 3s
  3100K .......... .......... .......... .......... .......... 24% 36.2M 3s
  3150K .......... .......... .......... .......... .......... 24% 54.1M 3s
  3200K .......... .......... .......... .......... .......... 24%  102M 3s
  3250K .......... .......... .......... .......... .......... 25%  248K 4s
  3300K .......... .......... .......... .......... .......... 25% 42.2M 4s
  3350K ....

  8100K .......... .......... .......... .......... .......... 62% 48.2M 2s
  8150K .......... .......... .......... .......... .......... 62% 35.3M 2s
  8200K .......... .......... .......... .......... .......... 63% 35.1M 2s
  8250K .......... .......... .......... .......... .......... 63% 26.5M 2s
  8300K .......... .......... .......... .......... .......... 63% 52.6M 2s
  8350K .......... .......... .......... .......... .......... 64% 30.5M 2s
  8400K .......... .......... .......... .......... .......... 64% 32.9M 2s
  8450K .......... .......... .......... .......... .......... 64% 26.9M 1s
  8500K .......... .......... .......... .......... .......... 65% 58.6M 1s
  8550K .......... .......... .......... .......... .......... 65% 75.1M 1s
  8600K .......... .......... .......... .......... .......... 66%  245K 2s
  8650K .......... .......... .......... .......... .......... 66% 39.3M 1s
  8700K .......... .......... .......... .......... .......... 66% 27.0M 1s
  8750K ....

   100K .......... .......... .......... .......... ..........  0% 3.68M 76s
   150K .......... .......... .......... .......... ..........  0% 8.05M 59s
   200K .......... .......... .......... .......... ..........  0% 1.18M 58s
   250K .......... .......... .......... .......... ..........  0% 5.40M 50s
   300K .......... .......... .......... .......... ..........  0% 14.4M 44s
   350K .......... .......... .......... .......... ..........  0% 12.4M 39s
   400K .......... .......... .......... .......... ..........  0% 1.62M 39s
   450K .......... .......... .......... .......... ..........  0% 6.57M 36s
   500K .......... .......... .......... .......... ..........  0% 13.1M 33s
   550K .......... .......... .......... .......... ..........  0% 3.77M 32s
   600K .......... .......... .......... .......... ..........  0% 31.9M 29s
   650K .......... .......... .......... .......... ..........  1% 5.51M 28s
   700K .......... .......... .......... .......... ..........  1% 8.66M 27s

  5450K .......... .......... .......... .......... ..........  8% 24.1M 21s
  5500K .......... .......... .......... .......... ..........  8% 39.8M 21s
  5550K .......... .......... .......... .......... ..........  8% 36.4M 20s
  5600K .......... .......... .......... .......... ..........  8% 79.1M 20s
  5650K .......... .......... .......... .......... ..........  8% 51.6M 20s
  5700K .......... .......... .......... .......... ..........  8% 36.1M 20s
  5750K .......... .......... .......... .......... ..........  8% 42.0M 20s
  5800K .......... .......... .......... .......... ..........  8% 35.3M 19s
  5850K .......... .......... .......... .......... ..........  8% 27.4M 19s
  5900K .......... .......... .......... .......... ..........  9% 76.5M 19s
  5950K .......... .......... .......... .......... ..........  9%  101M 19s
  6000K .......... .......... .......... .......... ..........  9%  246K 21s
  6050K .......... .......... .......... .......... ..........  9% 97.0M 21s

 10800K .......... .......... .......... .......... .......... 16% 45.5M 18s
 10850K .......... .......... .......... .......... .......... 16% 39.3M 18s
 10900K .......... .......... .......... .......... .......... 16% 77.9M 18s
 10950K .......... .......... .......... .......... .......... 16% 55.5M 18s
 11000K .......... .......... .......... .......... .......... 16% 56.2M 18s
 11050K .......... .......... .......... .......... .......... 16% 55.0M 18s
 11100K .......... .......... .......... .......... .......... 16% 56.4M 18s
 11150K .......... .......... .......... .......... .......... 16% 39.6M 18s
 11200K .......... .......... .......... .......... .......... 17%  246K 19s
 11250K .......... .......... .......... .......... .......... 17% 60.3M 18s
 11300K .......... .......... .......... .......... .......... 17% 43.8M 18s
 11350K .......... .......... .......... .......... .......... 17% 40.6M 18s
 11400K .......... .......... .......... .......... .......... 17% 59.4M 18s

 16150K .......... .......... .......... .......... .......... 24% 91.7M 16s
 16200K .......... .......... .......... .......... .......... 24% 68.6M 16s
 16250K .......... .......... .......... .......... .......... 24% 57.0M 16s
 16300K .......... .......... .......... .......... .......... 24% 73.9M 16s
 16350K .......... .......... .......... .......... .......... 24% 57.9M 16s
 16400K .......... .......... .......... .......... .......... 24% 42.6M 16s
 16450K .......... .......... .......... .......... .......... 25% 29.2M 16s
 16500K .......... .......... .......... .......... .......... 25% 52.6M 16s
 16550K .......... .......... .......... .......... .......... 25% 70.0M 16s
 16600K .......... .......... .......... .......... .......... 25%  247K 16s
 16650K .......... .......... .......... .......... .......... 25% 43.1M 16s
 16700K .......... .......... .......... .......... .......... 25% 76.2M 16s
 16750K .......... .......... .......... .......... .......... 25% 60.8M 16s

 21500K .......... .......... .......... .......... .......... 32% 55.0M 15s
 21550K .......... .......... .......... .......... .......... 32% 87.2M 15s
 21600K .......... .......... .......... .......... .......... 32% 76.6M 14s
 21650K .......... .......... .......... .......... .......... 32% 61.5M 14s
 21700K .......... .......... .......... .......... .......... 32% 87.0M 14s
 21750K .......... .......... .......... .......... .......... 33% 53.6M 14s
 21800K .......... .......... .......... .......... .......... 33% 68.8M 14s
 21850K .......... .......... .......... .......... .......... 33% 78.0M 14s
 21900K .......... .......... .......... .......... .......... 33%  247K 15s
 21950K .......... .......... .......... .......... .......... 33% 53.5M 15s
 22000K .......... .......... .......... .......... .......... 33% 71.7M 15s
 22050K .......... .......... .......... .......... .......... 33% 43.9M 14s
 22100K .......... .......... .......... .......... .......... 33% 44.9M 14s

 26850K .......... .......... .......... .......... .......... 40% 39.7M 13s
 26900K .......... .......... .......... .......... .......... 40% 28.4M 13s
 26950K .......... .......... .......... .......... .......... 40% 34.2M 13s
 27000K .......... .......... .......... .......... .......... 41% 57.3M 13s
 27050K .......... .......... .......... .......... .......... 41% 40.6M 13s
 27100K .......... .......... .......... .......... .......... 41% 25.3M 13s
 27150K .......... .......... .......... .......... .......... 41% 53.3M 13s
 27200K .......... .......... .......... .......... .......... 41% 75.4M 13s
 27250K .......... .......... .......... .......... .......... 41%  247K 13s
 27300K .......... .......... .......... .......... .......... 41% 46.9M 13s
 27350K .......... .......... .......... .......... .......... 41% 29.4M 13s
 27400K .......... .......... .......... .......... .......... 41% 35.7M 13s
 27450K .......... .......... .......... .......... .......... 41% 17.5M 13s

 32200K .......... .......... .......... .......... .......... 48% 50.3M 11s
 32250K .......... .......... .......... .......... .......... 48% 34.7M 11s
 32300K .......... .......... .......... .......... .......... 49% 28.7M 11s
 32350K .......... .......... .......... .......... .......... 49% 33.5M 11s
 32400K .......... .......... .......... .......... .......... 49% 49.7M 11s
 32450K .......... .......... .......... .......... .......... 49% 72.2M 11s
 32500K .......... .......... .......... .......... .......... 49% 51.3M 11s
 32550K .......... .......... .......... .......... .......... 49% 46.1M 11s
 32600K .......... .......... .......... .......... .......... 49% 29.7M 11s
 32650K .......... .......... .......... .......... .......... 49%  243K 11s
 32700K .......... .......... .......... .......... .......... 49% 39.3M 11s
 32750K .......... .......... .......... .......... .......... 49% 59.4M 11s
 32800K .......... .......... .......... .......... .......... 49% 46.4M 11s

 37550K .......... .......... .......... .......... .......... 56% 56.3M 9s
 37600K .......... .......... .......... .......... .......... 57% 41.8M 9s
 37650K .......... .......... .......... .......... .......... 57% 75.5M 9s
 37700K .......... .......... .......... .......... .......... 57% 53.8M 9s
 37750K .......... .......... .......... .......... .......... 57% 59.1M 9s
 37800K .......... .......... .......... .......... .......... 57% 36.4M 9s
 37850K .......... .......... .......... .......... .......... 57% 58.3M 9s
 37900K .......... .......... .......... .......... .......... 57% 65.8M 9s
 37950K .......... .......... .......... .......... .......... 57% 44.3M 9s
 38000K .......... .......... .......... .......... .......... 57%  247K 9s
 38050K .......... .......... .......... .......... .......... 57% 35.3M 9s
 38100K .......... .......... .......... .......... .......... 57% 45.0M 9s
 38150K .......... .......... .......... .......... .......... 57% 52.7M 9s
 38200K ....

 42950K .......... .......... .......... .......... .......... 65% 52.2M 8s
 43000K .......... .......... .......... .......... .......... 65% 58.4M 7s
 43050K .......... .......... .......... .......... .......... 65% 60.6M 7s
 43100K .......... .......... .......... .......... .......... 65% 37.8M 7s
 43150K .......... .......... .......... .......... .......... 65% 12.6M 7s
 43200K .......... .......... .......... .......... .......... 65% 50.0M 7s
 43250K .......... .......... .......... .......... .......... 65% 64.3M 7s
 43300K .......... .......... .......... .......... .......... 65%  247K 7s
 43350K .......... .......... .......... .......... .......... 65%  238M 7s
 43400K .......... .......... .......... .......... .......... 65%  335M 7s
 43450K .......... .......... .......... .......... .......... 65%  197M 7s
 43500K .......... .......... .......... .......... .......... 66%  163M 7s
 43550K .......... .......... .......... .......... .......... 66%  274M 7s
 43600K ....

 48350K .......... .......... .......... .......... .......... 73% 47.2M 6s
 48400K .......... .......... .......... .......... .......... 73% 50.1M 6s
 48450K .......... .......... .......... .......... .......... 73% 48.7M 6s
 48500K .......... .......... .......... .......... .......... 73% 45.4M 6s
 48550K .......... .......... .......... .......... .......... 73% 51.1M 6s
 48600K .......... .......... .......... .......... .......... 73%  245K 6s
 48650K .......... .......... .......... .......... .......... 73% 41.7M 6s
 48700K .......... .......... .......... .......... .......... 73% 35.2M 6s
 48750K .......... .......... .......... .......... .......... 73% 40.8M 6s
 48800K .......... .......... .......... .......... .......... 74% 45.3M 6s
 48850K .......... .......... .......... .......... .......... 74% 90.7M 6s
 48900K .......... .......... .......... .......... .......... 74% 48.7M 6s
 48950K .......... .......... .......... .......... .......... 74% 59.8M 6s
 49000K ....

 53750K .......... .......... .......... .......... .......... 81%  130M 4s
 53800K .......... .......... .......... .......... .......... 81%  191M 4s
 53850K .......... .......... .......... .......... .......... 81%  215M 4s
 53900K .......... .......... .......... .......... .......... 81%  246K 4s
 53950K .......... .......... .......... .......... .......... 81% 38.4M 4s
 54000K .......... .......... .......... .......... .......... 81% 46.6M 4s
 54050K .......... .......... .......... .......... .......... 82% 31.0M 4s
 54100K .......... .......... .......... .......... .......... 82% 39.0M 4s
 54150K .......... .......... .......... .......... .......... 82% 46.6M 4s
 54200K .......... .......... .......... .......... .......... 82% 58.4M 4s
 54250K .......... .......... .......... .......... .......... 82% 51.3M 4s
 54300K .......... .......... .......... .......... .......... 82% 38.9M 4s
 54350K .......... .......... .......... .......... .......... 82% 21.2M 4s
 54400K ....

 59150K .......... .......... .......... .......... .......... 89% 32.5M 2s
 59200K .......... .......... .......... .......... .......... 89%  243K 2s
 59250K .......... .......... .......... .......... .......... 89% 80.8M 2s
 59300K .......... .......... .......... .......... .......... 89%  173M 2s
 59350K .......... .......... .......... .......... .......... 90%  172M 2s
 59400K .......... .......... .......... .......... .......... 90%  198M 2s
 59450K .......... .......... .......... .......... .......... 90%  220M 2s
 59500K .......... .......... .......... .......... .......... 90%  150M 2s
 59550K .......... .......... .......... .......... .......... 90%  199M 2s
 59600K .......... .......... .......... .......... .......... 90%  221M 2s
 59650K .......... .......... .......... .......... .......... 90%  172M 2s
 59700K .......... .......... .......... .......... .......... 90%  156M 2s
 59750K .......... .......... .......... .......... .......... 90%  169M 2s
 59800K ....

 64550K .......... .......... .......... .......... .......... 97% 34.0M 0s
 64600K .......... .......... .......... .......... .......... 98% 70.9M 0s
 64650K .......... .......... .......... .......... .......... 98% 53.1M 0s
 64700K .......... .......... .......... .......... .......... 98% 18.1M 0s
 64750K .......... .......... .......... .......... .......... 98% 48.1M 0s
 64800K .......... .......... .......... .......... .......... 98% 37.1M 0s
 64850K .......... .......... .......... .......... .......... 98% 43.9M 0s
 64900K .......... .......... .......... .......... .......... 98% 62.4M 0s
 64950K .......... .......... .......... .......... .......... 98% 39.4M 0s
 65000K .......... .......... .......... .......... .......... 98% 50.8M 0s
 65050K .......... .......... .......... .......... .......... 98% 98.2M 0s
 65100K .......... .......... .......... .......... .......... 98%  246K 0s
 65150K .......... .......... .......... .......... .......... 98% 40.7M 0s
 65200K ....

  3600K .......... .......... .......... .......... ..........  4% 57.9M 26s
  3650K .......... .......... .......... .......... ..........  4% 51.4M 26s
  3700K .......... .......... .......... .......... ..........  4% 83.5M 25s
  3750K .......... .......... .......... .......... ..........  5% 51.3M 25s
  3800K .......... .......... .......... .......... ..........  5% 48.3M 25s
  3850K .......... .......... .......... .......... ..........  5% 41.5M 24s
  3900K .......... .......... .......... .......... ..........  5% 59.6M 24s
  3950K .......... .......... .......... .......... ..........  5% 87.3M 24s
  4000K .......... .......... .......... .......... ..........  5%  127M 23s
  4050K .......... .......... .......... .......... ..........  5% 69.9M 23s
  4100K .......... .......... .......... .......... ..........  5% 23.6M 23s
  4150K .......... .......... .......... .......... ..........  5% 42.2M 23s
  4200K .......... .......... .......... .......... ..........  5%  246K 26s

  8950K .......... .......... .......... .......... .......... 11% 34.8M 22s
  9000K .......... .......... .......... .......... .......... 11% 14.0M 22s
  9050K .......... .......... .......... .......... .......... 12% 33.9M 22s
  9100K .......... .......... .......... .......... .......... 12% 43.7M 22s
  9150K .......... .......... .......... .......... .......... 12% 40.6M 22s
  9200K .......... .......... .......... .......... .......... 12% 37.6M 22s
  9250K .......... .......... .......... .......... .......... 12% 47.2M 22s
  9300K .......... .......... .......... .......... .......... 12% 97.2M 21s
  9350K .......... .......... .......... .......... .......... 12% 62.1M 21s
  9400K .......... .......... .......... .......... .......... 12% 41.2M 21s
  9450K .......... .......... .......... .......... .......... 12%  246K 23s
  9500K .......... .......... .......... .......... .......... 12% 68.1M 22s
  9550K .......... .......... .......... .......... .......... 12%  102M 22s

 14300K .......... .......... .......... .......... .......... 19% 60.5M 20s
 14350K .......... .......... .......... .......... .......... 19% 42.4M 20s
 14400K .......... .......... .......... .......... .......... 19% 51.1M 20s
 14450K .......... .......... .......... .......... .......... 19% 63.4M 20s
 14500K .......... .......... .......... .......... .......... 19% 88.8M 20s
 14550K .......... .......... .......... .......... .......... 19% 30.5M 20s
 14600K .......... .......... .......... .......... .......... 19% 60.2M 20s
 14650K .......... .......... .......... .......... .......... 19% 33.0M 20s
 14700K .......... .......... .......... .......... .......... 19%  248K 20s
 14750K .......... .......... .......... .......... .......... 19%  132M 20s
 14800K .......... .......... .......... .......... .......... 19%  206M 20s
 14850K .......... .......... .......... .......... .......... 19%  210M 20s
 14900K .......... .......... .......... .......... .......... 19%  252M 20s

 19650K .......... .......... .......... .......... .......... 26%  148M 18s
 19700K .......... .......... .......... .......... .......... 26%  151M 18s
 19750K .......... .......... .......... .......... .......... 26%  135M 18s
 19800K .......... .......... .......... .......... .......... 26%  166M 18s
 19850K .......... .......... .......... .......... .......... 26%  195M 18s
 19900K .......... .......... .......... .......... .......... 26%  246K 18s
 19950K .......... .......... .......... .......... .......... 26% 47.7M 18s
 20000K .......... .......... .......... .......... .......... 26% 61.2M 18s
 20050K .......... .......... .......... .......... .......... 26% 17.5M 18s
 20100K .......... .......... .......... .......... .......... 26% 33.9M 18s
 20150K .......... .......... .......... .......... .......... 26% 35.3M 18s
 20200K .......... .......... .......... .......... .......... 26% 36.8M 18s
 20250K .......... .......... .......... .......... .......... 26% 47.1M 18s

 25000K .......... .......... .......... .......... .......... 33%  223M 16s
 25050K .......... .......... .......... .......... .......... 33%  249K 17s
 25100K .......... .......... .......... .......... .......... 33% 56.0M 17s
 25150K .......... .......... .......... .......... .......... 33%  103M 17s
 25200K .......... .......... .......... .......... .......... 33%  138M 17s
 25250K .......... .......... .......... .......... .......... 33%  126M 17s
 25300K .......... .......... .......... .......... .......... 33%  135M 16s
 25350K .......... .......... .......... .......... .......... 33%  102M 16s
 25400K .......... .......... .......... .......... .......... 33%  140M 16s
 25450K .......... .......... .......... .......... .......... 33%  102M 16s
 25500K .......... .......... .......... .......... .......... 33%  129M 16s
 25550K .......... .......... .......... .......... .......... 33% 82.7M 16s
 25600K .......... .......... .......... .......... .......... 33%  202M 16s

 30350K .......... .......... .......... .......... .......... 40% 39.5M 15s
 30400K .......... .......... .......... .......... .......... 40% 49.1M 15s
 30450K .......... .......... .......... .......... .......... 40% 29.1M 15s
 30500K .......... .......... .......... .......... .......... 40% 37.0M 15s
 30550K .......... .......... .......... .......... .......... 40% 38.6M 15s
 30600K .......... .......... .......... .......... .......... 40% 38.4M 15s
 30650K .......... .......... .......... .......... .......... 40% 34.9M 15s
 30700K .......... .......... .......... .......... .......... 40% 50.6M 15s
 30750K .......... .......... .......... .......... .......... 40% 26.3M 15s
 30800K .......... .......... .......... .......... .......... 40% 26.4M 15s
 30850K .......... .......... .......... .......... .......... 40% 28.1M 14s
 30900K .......... .......... .......... .......... .......... 41% 49.7M 14s
 30950K .......... .......... .......... .......... .......... 41% 49.7M 14s

 35700K .......... .......... .......... .......... .......... 47% 45.8M 13s
 35750K .......... .......... .......... .......... .......... 47% 62.9M 13s
 35800K .......... .......... .......... .......... .......... 47% 58.3M 13s
 35850K .......... .......... .......... .......... .......... 47% 62.5M 13s
 35900K .......... .......... .......... .......... .......... 47% 70.5M 13s
 35950K .......... .......... .......... .......... .......... 47% 62.7M 13s
 36000K .......... .......... .......... .......... .......... 47% 90.1M 13s
 36050K .......... .......... .......... .......... .......... 47% 45.2M 13s
 36100K .......... .......... .......... .......... .......... 47% 51.2M 13s
 36150K .......... .......... .......... .......... .......... 47% 45.4M 13s
 36200K .......... .......... .......... .......... .......... 48% 26.1M 13s
 36250K .......... .......... .......... .......... .......... 48% 52.9M 13s
 36300K .......... .......... .......... .......... .......... 48%  247K 13s

 41050K .......... .......... .......... .......... .......... 54% 52.5M 11s
 41100K .......... .......... .......... .......... .......... 54% 34.6M 11s
 41150K .......... .......... .......... .......... .......... 54% 25.0M 11s
 41200K .......... .......... .......... .......... .......... 54% 34.9M 11s
 41250K .......... .......... .......... .......... .......... 54% 30.6M 11s
 41300K .......... .......... .......... .......... .......... 54% 42.7M 11s
 41350K .......... .......... .......... .......... .......... 54% 30.1M 11s
 41400K .......... .......... .......... .......... .......... 54% 39.4M 11s
 41450K .......... .......... .......... .......... .......... 55% 69.1M 11s
 41500K .......... .......... .......... .......... .......... 55% 84.0M 11s
 41550K .......... .......... .......... .......... .......... 55%  248K 11s
 41600K .......... .......... .......... .......... .......... 55% 20.5M 11s
 41650K .......... .......... .......... .......... .......... 55% 29.1M 11s

 46400K .......... .......... .......... .......... .......... 61% 46.3M 10s
 46450K .......... .......... .......... .......... .......... 61% 44.1M 9s
 46500K .......... .......... .......... .......... .......... 61% 36.0M 9s
 46550K .......... .......... .......... .......... .......... 61% 26.8M 9s
 46600K .......... .......... .......... .......... .......... 61% 36.2M 9s
 46650K .......... .......... .......... .......... .......... 61% 26.0M 9s
 46700K .......... .......... .......... .......... .......... 61% 31.3M 9s
 46750K .......... .......... .......... .......... .......... 62% 31.2M 9s
 46800K .......... .......... .......... .......... .......... 62% 30.2M 9s
 46850K .......... .......... .......... .......... .......... 62% 22.6M 9s
 46900K .......... .......... .......... .......... .......... 62% 35.5M 9s
 46950K .......... .......... .......... .......... .......... 62%  244K 9s
 47000K .......... .......... .......... .......... .......... 62% 37.1M 9s
 47050K ...

 51800K .......... .......... .......... .......... .......... 68%  175M 8s
 51850K .......... .......... .......... .......... .......... 68%  176M 8s
 51900K .......... .......... .......... .......... .......... 68%  186M 8s
 51950K .......... .......... .......... .......... .......... 68%  131M 8s
 52000K .......... .......... .......... .......... .......... 68%  162M 8s
 52050K .......... .......... .......... .......... .......... 69%  170M 8s
 52100K .......... .......... .......... .......... .......... 69%  145M 8s
 52150K .......... .......... .......... .......... .......... 69%  142M 8s
 52200K .......... .......... .......... .......... .......... 69%  184M 8s
 52250K .......... .......... .......... .......... .......... 69%  184M 8s
 52300K .......... .......... .......... .......... .......... 69%  245K 8s
 52350K .......... .......... .......... .......... .......... 69% 46.2M 8s
 52400K .......... .......... .......... .......... .......... 69% 48.6M 8s
 52450K ....

 57200K .......... .......... .......... .......... .......... 75% 55.0M 6s
 57250K .......... .......... .......... .......... .......... 75% 55.3M 6s
 57300K .......... .......... .......... .......... .......... 76% 48.1M 6s
 57350K .......... .......... .......... .......... .......... 76% 40.6M 6s
 57400K .......... .......... .......... .......... .......... 76% 42.1M 6s
 57450K .......... .......... .......... .......... .......... 76% 42.5M 6s
 57500K .......... .......... .......... .......... .......... 76% 60.2M 6s
 57550K .......... .......... .......... .......... .......... 76% 87.4M 6s
 57600K .......... .......... .......... .......... .......... 76%  247K 6s
 57650K .......... .......... .......... .......... .......... 76% 32.1M 6s
 57700K .......... .......... .......... .......... .......... 76% 34.3M 6s
 57750K .......... .......... .......... .......... .......... 76% 33.7M 6s
 57800K .......... .......... .......... .......... .......... 76% 43.0M 6s
 57850K ....

 62600K .......... .......... .......... .......... .......... 83% 83.7M 4s
 62650K .......... .......... .......... .......... .......... 83% 91.1M 4s
 62700K .......... .......... .......... .......... .......... 83% 71.5M 4s
 62750K .......... .......... .......... .......... .......... 83% 26.3M 4s
 62800K .......... .......... .......... .......... .......... 83% 95.9M 4s
 62850K .......... .......... .......... .......... .......... 83% 95.0M 4s
 62900K .......... .......... .......... .......... .......... 83% 80.6M 4s
 62950K .......... .......... .......... .......... .......... 83%  246K 4s
 63000K .......... .......... .......... .......... .......... 83% 52.3M 4s
 63050K .......... .......... .......... .......... .......... 83% 42.4M 4s
 63100K .......... .......... .......... .......... .......... 83% 59.5M 4s
 63150K .......... .......... .......... .......... .......... 83% 31.2M 4s
 63200K .......... .......... .......... .......... .......... 83% 27.5M 4s
 63250K ....

 68000K .......... .......... .......... .......... .......... 90% 51.8M 2s
 68050K .......... .......... .......... .......... .......... 90% 40.1M 2s
 68100K .......... .......... .......... .......... .......... 90% 38.5M 2s
 68150K .......... .......... .......... .......... .......... 90% 42.7M 2s
 68200K .......... .......... .......... .......... .......... 90% 39.3M 2s
 68250K .......... .......... .......... .......... .......... 90% 28.9M 2s
 68300K .......... .......... .......... .......... .......... 90%  246K 2s
 68350K .......... .......... .......... .......... .......... 90% 17.4M 2s
 68400K .......... .......... .......... .......... .......... 90% 45.8M 2s
 68450K .......... .......... .......... .......... .......... 90% 46.4M 2s
 68500K .......... .......... .......... .......... .......... 90% 55.9M 2s
 68550K .......... .......... .......... .......... .......... 90% 38.6M 2s
 68600K .......... .......... .......... .......... .......... 90% 44.4M 2s
 68650K ....

 73400K .......... .......... .......... .......... .......... 97%  358M 1s
 73450K .......... .......... .......... .......... .......... 97%  249K 1s
 73500K .......... .......... .......... .......... .......... 97%  139M 1s
 73550K .......... .......... .......... .......... .......... 97%  140M 1s
 73600K .......... .......... .......... .......... .......... 97%  337M 1s
 73650K .......... .......... .......... .......... .......... 97%  231M 1s
 73700K .......... .......... .......... .......... .......... 97%  188M 1s
 73750K .......... .......... .......... .......... .......... 97%  182M 1s
 73800K .......... .......... .......... .......... .......... 97%  154M 1s
 73850K .......... .......... .......... .......... .......... 97%  148M 1s
 73900K .......... .......... .......... .......... .......... 98%  229M 0s
 73950K .......... .......... .......... .......... .......... 98%  222M 0s
 74000K .......... .......... .......... .......... .......... 98%  191M 0s
 74050K ....

  3050K .......... .......... .......... .......... .......... 23% 65.3M 4s
  3100K .......... .......... .......... .......... .......... 24% 64.6M 3s
  3150K .......... .......... .......... .......... .......... 24% 38.7M 3s
  3200K .......... .......... .......... .......... .......... 24% 68.5M 3s
  3250K .......... .......... .......... .......... .......... 25% 47.1M 3s
  3300K .......... .......... .......... .......... .......... 25% 50.5M 3s
  3350K .......... .......... .......... .......... .......... 25% 76.9M 3s
  3400K .......... .......... .......... .......... .......... 26% 39.9M 3s
  3450K .......... .......... .......... .......... .......... 26% 49.6M 3s
  3500K .......... .......... .......... .......... .......... 27% 83.3M 3s
  3550K .......... .......... .......... .......... .......... 27%  248K 3s
  3600K .......... .......... .......... .......... .......... 27% 39.6M 3s
  3650K .......... .......... .......... .......... .......... 28% 54.2M 3s
  3700K ....

  8450K .......... .......... .......... .......... .......... 64% 78.7M 2s
  8500K .......... .......... .......... .......... .......... 65% 37.1M 2s
  8550K .......... .......... .......... .......... .......... 65% 23.7M 1s
  8600K .......... .......... .......... .......... .......... 66% 28.0M 1s
  8650K .......... .......... .......... .......... .......... 66% 46.4M 1s
  8700K .......... .......... .......... .......... .......... 66% 29.8M 1s
  8750K .......... .......... .......... .......... .......... 67% 36.7M 1s
  8800K .......... .......... .......... .......... .......... 67% 19.9M 1s
  8850K .......... .......... .......... .......... .......... 68% 64.3M 1s
  8900K .......... .......... .......... .......... .......... 68%  245K 1s
  8950K .......... .......... .......... .......... .......... 68% 61.9M 1s
  9000K .......... .......... .......... .......... .......... 69% 38.1M 1s
  9050K .......... .......... .......... .......... .......... 69% 46.8M 1s
  9100K ....

   450K .......... .......... .......... .......... .......... 21% 5.55M 1s
   500K .......... .......... .......... .......... .......... 23% 4.48M 1s
   550K .......... .......... .......... .......... .......... 25% 10.4M 1s
   600K .......... .......... .......... .......... .......... 27% 12.7M 1s
   650K .......... .......... .......... .......... .......... 29% 6.65M 1s
   700K .......... .......... .......... .......... .......... 31% 34.6M 1s
   750K .......... .......... .......... .......... .......... 33% 1.59M 1s
   800K .......... .......... .......... .......... .......... 36% 6.11M 1s
   850K .......... .......... .......... .......... .......... 38% 11.3M 1s
   900K .......... .......... .......... .......... .......... 40% 2.91M 1s
   950K .......... .......... .......... .......... .......... 42% 5.16M 1s
  1000K .......... .......... .......... .......... .......... 44% 15.9M 1s
  1050K .......... .......... .......... .......... .......... 46% 15.5M 0s
  1100K ....

   150K .......... .......... .......... .......... .......... 52% 3.18M 0s
   200K .......... .......... .......... .......... .......... 66% 12.0M 0s
   250K .......... .......... .......... .......... .......... 79% 1.41M 0s
   300K .......... .......... .......... .......... .......... 92% 5.15M 0s
   350K .......... .......... ........                        100%  101M=0.3s

2022-06-10 13:58:03 (1.30 MB/s) - ‘9402_2021_dayl.nc’ saved [387092/387092]



In [7]:
%%sh 
ls -lt 13166_*_dayl.nc 11933_*_dayl.nc 9402_*_dayl.nc

-rw-r--r-- 1 jrw jrw   387092 Jun 10 13:58 9402_2021_dayl.nc
-rw-r--r-- 1 jrw jrw  2673611 Jun 10 13:57 11933_2021_dayl.nc
-rw-r--r-- 1 jrw jrw  2412605 Jun 10 13:57 13166_2021_dayl.nc
-rw-r--r-- 1 jrw jrw 13392940 Jun 10 13:57 9402_2020_dayl.nc
-rw-r--r-- 1 jrw jrw 77252276 Jun 10 13:57 11933_2020_dayl.nc
-rw-r--r-- 1 jrw jrw 67551788 Jun 10 13:56 13166_2020_dayl.nc
-rw-r--r-- 1 jrw jrw 13392940 Jun 10 13:56 9402_2019_dayl.nc
-rw-r--r-- 1 jrw jrw 77252276 Jun 10 13:56 11933_2019_dayl.nc
-rw-r--r-- 1 jrw jrw 67551788 Jun 10 13:55 13166_2019_dayl.nc


Download all 1980 nc files for tile 11210 with **curl** instead of wget

In [8]:
%%sh
bash ../Bash/daymet_tile-nc-retrieval.sh -s 1980 -e 1980 -c -t "11210"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.4M  100 76.4M    0     0  3071k      0  0:00:25  0:00:25 --:--:-- 3072k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.4M  100 76.4M    0     0  3072k      0  0:00:25  0:00:25 --:--:-- 7618k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.4M  100 76.4M    0     0  3072k      0  0:00:25  0:00:25 --:--:-- 3072k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.4M  100 76.4M    0     0  3072k      0  0:00:25  0:00:25 --:--:-- 3073k
  % Total    % Received % Xferd  Average Speed   Tim

In [9]:
%%sh
ls -lt 11210_1980_*.nc

-rw-r--r-- 1 jrw jrw 80180752 Jun 10 14:03 11210_1980_vp.nc
-rw-r--r-- 1 jrw jrw 80180760 Jun 10 14:02 11210_1980_tmin.nc
-rw-r--r-- 1 jrw jrw 80180760 Jun 10 14:02 11210_1980_tmax.nc
-rw-r--r-- 1 jrw jrw 80180752 Jun 10 14:01 11210_1980_swe.nc
-rw-r--r-- 1 jrw jrw 80180772 Jun 10 14:01 11210_1980_srad.nc
-rw-r--r-- 1 jrw jrw 80180752 Jun 10 14:01 11210_1980_prcp.nc
-rw-r--r-- 1 jrw jrw 80180724 Jun 10 14:00 11210_1980_dayl.nc
